<?php
$title = "Offline Remotii's";
$this->headTitle($title);

$base_url = BASE_URL . '/assets/b';
?>

<div class="pageInfo"><h1>Offline Remotii's</h1></div>
<?php if (!empty($response)) { ?>
    <div id="response" class="<?php echo $response['status']; ?>"><?php echo $response['message']; ?></div>
<?php } ?>

<div class="widget listselect">       
    <div id="dyn" class="hiddenpars"> 
        <table cellpadding="0" cellspacing="0" border="0" class="dTable2 listRemotii" id="dynamic2">
            <thead>
                <tr>
                    <th width="120">Remotii Account Name</th>
                    <th width="140">Remotii Name</th>
                    <th style="width:150px !important;">Detection Time</th>
                    <th style="width:150px !important;">Last Communication Time</th>
                    <th style="width:150px !important;">Private IP Address</th>
                    <th style="width:150px !important;">Remotii Timezone</th>

                </tr>
            </thead>

            <tbody>
                <?php
                foreach ($data as $rData) {
                    ?>
                    <tr>
                        <td>
                            <a href="<?php print BASE_URL . '/admin/index/clientinfo/' . $rData['user_id']; ?>"><?php if ($rData['user_role'] != 2) print $rData['username']; ?></a>
                        </td> 

                        <td><?php print $rData['remotii_name']; ?></td>


                        <td>
                            <?php
                            $MaxTime = $rData['last_offline_detection_timestamp'] + (int) $rData['offset'] * 60;
                            if ($MaxTime > 0 && $rData['last_offline_detection_timestamp'] > 0) {
                                $FormattedTime = date('m/d/Y H:i:s', $MaxTime);
                                $time_with_space = '';
                                for ($i = 0; $i < strlen($FormattedTime); $i++) {
                                    if ($FormattedTime{$i} == ' ' && $i <= 15) {
                                        $time_with_space = $time_with_space . '&nbsp&nbsp' . $FormattedTime{$i};
                                    } else {
                                        $time_with_space = $time_with_space . $FormattedTime{$i};
                                    }
                                }

                                print $time_with_space . ($rData['abbr'] ? " (" . $rData['abbr'] . ")" : '')." (Server time)";
                            } else {
                                print $rData['last_offline_detection_timestamp'];
                            }
                            ?>
                        </td>

                        <td> <?php
                            $MaxTime = $rData['max_recieve_time'] + (int) $rData['offset'] * 60;
                            if ($MaxTime > 0 && $rData['max_recieve_time'] > 0) {
                                $FormattedTime = date('m/d/Y H:i:s', $MaxTime);
                                $time_with_space = '';
                                for ($i = 0; $i < strlen($FormattedTime); $i++) {
                                    if ($FormattedTime{$i} == ' ' && $i <= 15) {
                                        $time_with_space = $time_with_space . '&nbsp&nbsp' . $FormattedTime{$i};
                                    } else {
                                        $time_with_space = $time_with_space . $FormattedTime{$i};
                                    }
                                }

                                print $time_with_space . ($rData['abbr'] ? " (" . $rData['abbr'] . ")" : '')." (Server time)";
                            } else {
                                print $rData['max_recieve_time'];
                            }
                            ?>
                        </td>
                        <td><?php print $rData['local_ip_address'] ? $rData['local_ip_address'] : '';
                            ?>
                        </td>

                        <td><?php
                            $time = 0;
                            if ($rData['day_light_saving'] == 0) {
                                $time = $rData['offset'];
                            }
                            if ($rData['day_light_saving'] == 1) {
                                $time = $rData['offset'];
                                $time = $time - 60;
                            }
                            $hour = intval($time / 60);


                            $minutes = $time % 60;

                            $Time = '+00:00';

                            if ($time < 0) {
                                $hour = -$hour;
                                $minutes = -$minutes;
                                if ($hour < 10) {
                                    if ($minutes < 10) {
                                        $Time = "-0$hour:0$minutes";
                                    }
                                    if ($minutes >= 10) {
                                        $Time = "-0$hour:$minutes";
                                    }
                                }

                                if ($hour >= 10) {
                                    if ($minutes < 10) {
                                        $Time = "-$hour:0$minutes";
                                    }
                                    if ($minutes > 10) {
                                        $Time = "-$hour:$minutes";
                                    }
                                }
                            }
                            if ($time > 0) {
                                if ($hour < 10) {
                                    if ($minutes < 10) {
                                        $Time = "+0$hour:0$minutes";
                                    }
                                    if ($minutes >= 10) {
                                        $Time = "+0$hour:$minutes";
                                    }
                                }

                                if ($hour >= 10) {
                                    if ($minutes < 10) {
                                        $Time = "+$hour:0$minutes";
                                    }
                                    if ($minutes > 10) {
                                        $Time = "+$hour:$minutes";
                                    }
                                }
                            }

                            if ($rData['day_light_saving'] == 1) {
                                print ($rData['abbr'] ? $rData['abbr'] : '') . " (GMT " . $Time . " DST)";
                            } else {
                                print ($rData['abbr'] ? $rData['abbr'] : '') . " (GMT " . $Time . ")";
                            }
                            ?></td>
                    </tr>
                    <?php
                }
                ?>

            </tbody>
        </table>
    </div>
</div>
<!-- /widget --> 
