<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">   
    <h2>About</h2>
  </div>
</div>
<!-- Tag line ends --> 
<div class="content">
<div class="wrapper page-con">
	<h3 class="heading3">Remotii Inc. </h3>
	<p>At Remotii, Inc., our goal is to put control of everyday life at the user&apos;s fingertips.  We design hardware that allows people to monitor devices they select through a user friendly web page.  Remotii is all about the user!  The user decides what devices, house, and what requirement/specification will be monitored (entry/exit, temperature sensing, on/off, etc.).  We provide the interface to do it.  The possibilities are endless, and we do not seek to limit them.</p>
    <h3 class="heading3">Our Home </h3>
    <p>Remotii, Inc.  has two operating offices; one located in the greater Atlanta, GA area, the second in Boston, MA.</p>
	<div class="box1">
		<div class="inner form">
			<div class="quote">
				<p class="rit">Remotii is the perfect way to monitor and control all of your favorite devices. Before Remotii, the name of the game was device replacement. Remotii is a complete game changer that has the potential to save people a lot of money on device upgrades that don&apos;t yet need to be made.
			</p>
			<p class="name">President Remotii Inc.</p>
			</div>
			
		</div>
	</div>
	<h3 class="heading3">Our Values </h3>
	<p>At Remotii, Inc., we put the customer first.  We want the customer to be satisfied with the hardware, software and overall usability of our product and its interface.  We seek to provide friendly and prompt customer service.   At all times, it is our goal to provide customers with innovative technology, while never compromising the safety and security of our customer data.  Remotii, Inc. we will never sell or distribute to third parties any stored customer information. </p>
</div>
</div>
<!--/content-->





