<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">   
    <h2>About Remotii</h2>
  </div>
</div>
<!-- Tag line ends --> 
<div class="content">
<div class="wrapper page-con">
<h3 class="heading3">What is a Remotii</h3>
<p>Remotii is a way to bring sophisticated remote internet control and detailed logging to a 
lot of things that you already have that are not able to be seen or controlled on the web.
<p>

<p>Remotii can connect to most existing security systems, switch between normal and 
unoccupied area thermostats for vacation homes, let you know when the kids are 
home, or when the dog came in. Remotii uses normal switched circuits or 
outputs from wine chillers, water sensors and almost everything else to know when an 
event has occurred in your home or business. All you need to do is plug in Remotii, 
connect to the internet and start hooking up your devices. Each Remotii can show 4 
customized status signals on any computer or phone, send emails if desired, and send 
back 3 customized control signals to take physical action when desired. Additionally, Remotii 
can interface to the full family of Linear and other wireless receivers for those who 
prefer wireless detection devices. The uses are endless.</p>
</div>
</div>
<!--/content-->