<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">   
    <h2>Careers</h2>
  </div>
</div>
<!-- Tag line ends --> 
<div class="content">
<div class="wrapper page-con">
	<div class="car-img"><img src="<?php echo BASE_URL?>/assets/f/images/bulb.png"></div>
	<div class="tag">There are currently no openings.</div>
	<p>However, if you are interested in being part of the Remotii team, please feel free to drop us a line with your resume.  We will keep you in mind for when new positions open.</p>
</div>
</div>
<!--/content-->





