<?php
$baseUrl = BASE_URL . '/assets/b';
echo $this->doctype();

$spInputConfig = $this->InputConfig;
$spOutputConfig = $this->OutputConfig;
$greenColor = '#00CC00';
$redColor = '#FF0000';
$remotiiId; //  Contains the Remotii Id

//_pr($remotiiMacData);
//_pre($spInputConfig);
//_pre($spOutputConfig);

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Remotii')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>-->
        <?php
        $this->headMeta()->appendName("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", "viewport");
        $this->headLink()->appendStylesheet($baseUrl . '/css/styles.css');
        $this->headLink()->appendStylesheet($baseUrl . '/css/popup.css');
        $this->headLink()->appendStylesheet($baseUrl . '/css/screen.css');
        $this->headLink()->appendStylesheet($baseUrl . '/css/evol.colorpicker.css');

        echo $this->headlink();
        ?>
        <script src="<?php echo $baseUrl ?>/js/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $baseUrl ?>/js/easySlider1.7.js"></script>
        <script type="text/javascript" src="<?php echo $baseUrl ?>/js/jquery.maskedinput-1.3.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $baseUrl ?>/js/evol.colorpicker.js"></script>


        <script type="text/javascript">

            $(document).ready(function() {
                $("#slider ul li").css({width: '670px', height: '320px'});
                $("#slider").easySlider();

                $('.noIndColor').colorpicker({
                    displayIndicator: false,
                    width: "0px"
                });
                
                $("#macAddress").mask("**-**-**-**-**-**");
                
                $("#nextBtn").click(function() {
                    var pageno = $(".pageno span").text()


                    var ri_enabled_1 = $('#ri_enabled_1').is(':checked');
                    var ri_enabled_2 = $('#ri_enabled_2').is(':checked');
                    var ri_enabled_3 = $('#ri_enabled_3').is(':checked');
                    var ri_enabled_4 = $('#ri_enabled_4').is(':checked');

                    //alert('ri1en:'+ri_enabled_1+'ri2en:'+ri_enabled_2+'ri3en:'+ri_enabled_3+'ri4en:'+ri_enabled_4);

                    if ($("#ri_name_1").val() == "") {
                        ri_name_1 = '';
                    } else {
                        ri_name_1 = $("#ri_name_1").val();
                    }
                    $("#ri_input_name_1").text(ri_name_1);

                    if ($("#ri_asl_1").val() == "") {
                        ri_asl_1_val = 'Active Label';
                    } else {
                        ri_asl_1_val = $("#ri_asl_1").val();
                    }
                    $("#ri_active_label_1").text(ri_asl_1_val);

                    if ($("#ri_iasl_1").val() == "") {
                        ri_iasl_1_val = 'Inactive Label';
                    } else {
                        ri_iasl_1_val = $("#ri_iasl_1").val();
                    }
                    $("#ri_inactive_label_1").text(ri_iasl_1_val);


                    if (ri_enabled_1)
                    {
                        //$("#ri_enable_ntfn_1").attr("checked","checked");

                        $("#ri_enable_ntfn_1").attr("disabled", false);
                        $("#ri_ntfn_active_trigger_1").attr("disabled", false);
                        $("#ri_ntfn_inactive_trigger_1").attr("disabled", false);

                    } else {
                        $("#ri_enable_ntfn_1").attr("disabled", "disabled");
                        $("#ri_ntfn_active_trigger_1").attr("disabled", "disabled");
                        $("#ri_ntfn_inactive_trigger_1").attr("disabled", "disabled");
                    }

                    if (ri_enabled_2)
                    {
                        //$("#ri_enable_ntfn_2").attr("checked","checked");
                        $("#ri_input_name_2").text($("#ri_name_2").val());
                        $("#ri_active_label_2").text($("#ri_asl_2").val());
                        $("#ri_inactive_label_2").text($("#ri_iasl_2").val());

                        $("#ri_enable_ntfn_2").attr("disabled", false);
                        $("#ri_ntfn_active_trigger_2").attr("disabled", false);
                        $("#ri_ntfn_inactive_trigger_2").attr("disabled", false);

                    } else {
                        $("#ri_enable_ntfn_2").attr("disabled", "disabled");
                        $("#ri_ntfn_active_trigger_2").attr("disabled", "disabled");
                        $("#ri_ntfn_inactive_trigger_2").attr("disabled", "disabled");
                    }

                    if (ri_enabled_3)
                    {
                        //$("#ri_enable_ntfn_3").attr("checked","checked");
                        $("#ri_input_name_3").text($("#ri_name_3").val());
                        $("#ri_active_label_3").text($("#ri_asl_3").val());
                        $("#ri_inactive_label_3").text($("#ri_iasl_3").val());

                        $("#ri_enable_ntfn_3").attr("disabled", false);
                        $("#ri_ntfn_active_trigger_3").attr("disabled", false);
                        $("#ri_ntfn_inactive_trigger_3").attr("disabled", false);

                    } else {
                        $("#ri_enable_ntfn_3").attr("disabled", "disabled");
                        $("#ri_ntfn_active_trigger_3").attr("disabled", "disabled");
                        $("#ri_ntfn_inactive_trigger_3").attr("disabled", "disabled");
                    }

                    if (ri_enabled_4)
                    {
                        //$("#ri_enable_ntfn_4").attr("checked","checked");
                        $("#ri_input_name_4").text($("#ri_name_4").val());
                        $("#ri_active_label_4").text($("#ri_asl_4").val());
                        $("#ri_inactive_label_4").text($("#ri_iasl_4").val());

                        $("#ri_enable_ntfn_4").attr("disabled", false);
                        $("#ri_ntfn_active_trigger_4").attr("disabled", false);
                        $("#ri_ntfn_inactive_trigger_4").attr("disabled", false);

                    } else {
                        $("#ri_enable_ntfn_4").attr("disabled", "disabled");
                        $("#ri_ntfn_active_trigger_4").attr("disabled", "disabled");
                        $("#ri_ntfn_inactive_trigger_4").attr("disabled", "disabled");
                    }

                    var ro_enabled_1 = $('#ro_enabled_1').is(':checked');
                    var ro_enabled_2 = $('#ro_enabled_2').is(':checked');
                    var ro_enabled_3 = $('#ro_enabled_3').is(':checked');

                    if (ro_enabled_1)
                    {
                        //$("#ro_enable_ntfn_1").attr("checked","checked");
                        $("#ro_input_name_1").text($("#ro_name_1").val());
                        $("#ro_active_label_1").text($("#ro_asl_1").val());
                        $("#ro_inactive_label_1").text($("#ro_iasl_1").val());
                        $("#ro_step2_name_1").text($("#ro_name_1").val());
                        $("#ro_step2_active_label_1").text($("#ro_asl_1").val());
                        $("#ro_step2_inactive_label_1").text($("#ro_iasl_1").val());

                        $("#ro_momentary_1").attr("disabled", false);
                        $("#ro_active_initialState_1").attr("disabled", false);
                        $("#ro_inactive_initialState_1").attr("disabled", false);

                        $("#ro_enable_ntfn_1").attr("disabled", false);
                        $("#ro_ntfn_active_trigger_1").attr("disabled", false);
                        $("#ro_ntfn_inactive_trigger_1").attr("disabled", false);

                    } else {

                        $("#ro_momentary_1").attr("disabled", "disabled");
                        $("#ro_active_initialState_1").attr("disabled", "disabled");
                        $("#ro_inactive_initialState_1").attr("disabled", "disabled");

                        $("#ro_enable_ntfn_1").attr("disabled", "disabled");
                        $("#ro_ntfn_active_trigger_1").attr("disabled", "disabled");
                        $("#ro_ntfn_inactive_trigger_1").attr("disabled", "disabled");
                    }

                    if (ro_enabled_2)
                    {
                        //$("#ro_enable_ntfn_2").attr("checked","checked");
                        $("#ro_input_name_2").text($("#ro_name_2").val());
                        $("#ro_active_label_2").text($("#ro_asl_2").val());
                        $("#ro_inactive_label_2").text($("#ro_iasl_2").val());
                        $("#ro_step2_name_2").text($("#ro_name_2").val());
                        $("#ro_step2_active_label_2").text($("#ro_asl_2").val());
                        $("#ro_step2_inactive_label_2").text($("#ro_iasl_2").val());

                        $("#ro_momentary_2").attr("disabled", false);
                        $("#ro_active_initialState_2").attr("disabled", false);
                        $("#ro_inactive_initialState_2").attr("disabled", false);
                        $("#ro_enable_ntfn_2").attr("disabled", false);
                        $("#ro_ntfn_active_trigger_2").attr("disabled", false);
                        $("#ro_ntfn_inactive_trigger_2").attr("disabled", false);

                    } else {

                        $("#ro_momentary_2").attr("disabled", "disabled");
                        $("#ro_active_initialState_2").attr("disabled", "disabled");
                        $("#ro_inactive_initialState_2").attr("disabled", "disabled");

                        $("#ro_enable_ntfn_2").attr("disabled", "disabled");
                        $("#ro_ntfn_active_trigger_2").attr("disabled", "disabled");
                        $("#ro_ntfn_inactive_trigger_2").attr("disabled", "disabled");
                    }

                    if (ro_enabled_3)
                    {
                        //$("#ro_enable_ntfn_3").attr("checked","checked");
                        $("#ro_input_name_3").text($("#ro_name_3").val());
                        $("#ro_active_label_3").text($("#ro_asl_3").val());
                        $("#ro_inactive_label_3").text($("#ro_iasl_3").val());
                        $("#ro_step2_name_3").text($("#ro_name_3").val());
                        $("#ro_step2_active_label_3").text($("#ro_asl_3").val());
                        $("#ro_step2_inactive_label_3").text($("#ro_iasl_3").val());

                        $("#ro_momentary_3").attr("disabled", false);
                        $("#ro_active_initialState_3").attr("disabled", false);
                        $("#ro_inactive_initialState_3").attr("disabled", false);
                        $("#ro_enable_ntfn_3").attr("disabled", false);
                        $("#ro_ntfn_active_trigger_3").attr("disabled", false);
                        $("#ro_ntfn_inactive_trigger_3").attr("disabled", false);

                    } else {

                        $("#ro_momentary_3").attr("disabled", "disabled");
                        $("#ro_active_initialState_3").attr("disabled", "disabled");
                        $("#ro_inactive_initialState_3").attr("disabled", "disabled");

                        $("#ro_enable_ntfn_3").attr("disabled", "disabled");
                        $("#ro_ntfn_active_trigger_3").attr("disabled", "disabled");
                        $("#ro_ntfn_inactive_trigger_3").attr("disabled", "disabled");
                    }
                });

                $("#ri_enabled_1,#ri_enabled_2,#ri_enabled_3,#ri_enabled_4,#ro_enabled_1,#ro_enabled_2,#ro_enabled_3").click(function() {
                    var this_id = $(this).attr('id');
                    n = this_id.split("_");
                    id_first = n[0];
                    id_last = n[n.length - 1];

                    if ($(this).attr("checked")) {
                        $("#" + id_first + "_name_" + id_last).attr("disabled", false);
                        $("#" + id_first + "_asl_" + id_last).attr("disabled", false);
                        $("#" + id_first + "_iasl_" + id_last).attr("disabled", false);
                    } else {
                        $("#" + id_first + "_name_" + id_last).attr("disabled", "disabled").val("");
                        $("#" + id_first + "_asl_" + id_last).attr("disabled", "disabled").val("");
                        $("#" + id_first + "_iasl_" + id_last).attr("disabled", "disabled").val("");
                    }
                });
            });

        </script>
    </head>

    <body>
        <form name="form_default_remotii_setup" id="form_default_remotii_setup">	
            <input type="hidden" name="xDefaultRemotiiDataSubmission" value="true">
            <div class="remotii-setup modify"> 
                <h2>Remotii Setup Wizard<span style="float:right;font-size:15px;margin-right:20px;" class="pageno"><span>1</span>/10</span></h2>
                <div id="slider">
                    <ul>

                        <li>
                            <div>
                                <p id="foo">Hi.  This wizard will help you set default Remotii setup.<br> We just have a few questions </p>
                                <p><a href="#" title="Add Remotii Image"><img src="<?php echo $baseUrl ?>/images/wizard-img.jpg"></a></p>

                                <a class="btn-red " href="#">Cancel</a> 
                            </div>
                        </li>
                        
                        <li>
                            <div class="form rinput">
                                <input type="text" name="remotiiName" value="<?php print $remotiiMacData[0]['remotii_name']; ?>" placeholder="Remotii Name" />
                                <p>
                                    Your chosen Remotii name will be displayed to you on your Remotii data page so that you can easily identify this Remotii.
                                </p>
                                <input type="text" name="macAddress" value="<?php print $remotiiMacData[0]['mac_address']; ?>" id="macAddress" disabled="disabled" placeholder="Mac Address" />  <span id="errMsg" class="red"></span>
                                <p>
                                    You can find your MAC address on the bottom of your Remotii.
                                </p>
                            </div>
                        </li>

                        <li>
                            <p style="padding-top: 88px;">In this section, we will configure Remotii inputs.</p>
                        </li>


                        <li>
                            <div class="form rinput">
                                <table width="100%">
                                    <tr>
                                        <td>Enable</td>
                                        <td>Input Names</td>
                                        <td>Active Label</td>
                                        <td>Inactive Label</td>
                                    </tr>

                                    <?php
                                    for ($i = 1; $i <= 4; $i++):
                                        $j = $i - 1;
                                        if ($spInputConfig[$j]['is_enabled']) {
                                            $checked = 'checked="checked"';
                                            $name = $spInputConfig[$j]['name'];
                                            $activeLabelText = $spInputConfig[$j]['active_label_text'];
                                            $activeLabelColor = $spInputConfig[$j]['active_label_color'];
                                            $inactiveLabelText = $spInputConfig[$j]['inactive_label_text'];
                                            $inactiveLabelColor = $spInputConfig[$j]['inactive_label_color'];
                                            $isEnabled = $spInputConfig[$j]['is_enabled'];
                                            $enableNotification = $spInputConfig[$j]['enable_notification'];
                                            $notificationTrigger = $spInputConfig[$j]['notification_trigger'];
                                            $disabled = '';
                                        } else {
                                            $checked = '';
                                            $name = '';
                                            $activeLabelText = '';
                                            $activeLabelColor = $greenColor;
                                            $inactiveLabelText = '';
                                            $inactiveLabelColor = $redColor;
                                            $isEnabled = '';
                                            $enableNotification = '';
                                            $notificationTrigger = '';
                                            $disabled = 'disabled="disabled"';
                                        }
                                        ?>

                                        <tr>
                                            <td><input type="checkbox" <?php echo $checked; ?> name="ri_enabled_<?php echo $i; ?>" id="ri_enabled_<?php echo $i; ?>" ></td>
                                            <td><input <?php echo $disabled; ?> type="text" name="ri_name_<?php echo $i ?>" id="ri_name_<?php echo $i ?>" placeholder="Input<?php echo $i; ?> Name" value="<?php echo $name; ?>"></td>
                                            <td>
                                                <input <?php echo $disabled; ?> type="text" name="ri_asl_<?php echo $i; ?>" id="ri_asl_<?php echo $i; ?>" placeholder="Active Label" value="<?php echo $activeLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $activeLabelColor; ?>" name="ri_active_color_<?php echo $i; ?>"/>
                                                </div>	
                                            </td>
                                            <td>
                                                <input <?php echo $disabled; ?> type="text" name="ri_iasl_<?php echo $i; ?>" id="ri_iasl_<?php echo $i; ?>" placeholder="Inactive Label" value="<?php echo $inactiveLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $inactiveLabelColor; ?>" name="ri_inactive_color_<?php echo $i; ?>"/>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%">
                                    <tr>
                                        <th>Enable notifications</th> 
                                        <th>Input Names</th>
                                        <th>Notification Trigger</th>
                                        <th>Notification Email</th>
                                    </tr>
                                    <?php
                                    for ($i = 1; $i <= 4; $i++):
                                        $j = $i - 1;
                                        if ($spInputConfig[$j]['is_enabled']) {
                                            $name = $spInputConfig[$j]['name'];
                                            $notification_email = $spInputConfig[$j]['notification_email']; 
                                            $activeLabelText = $spInputConfig[$j]['active_label_text'];
                                            $inactiveLabelText = $spInputConfig[$j]['inactive_label_text'];

                                            if ($spInputConfig[$j]['enable_notification']) {
                                                $enableNotification = 'checked="checked"';
                                            } else {
                                                $enableNotification = '';
                                            }

                                            $notificationTriggerActive = '';
                                            $notificationTriggerInActive = '';
                                            if ($spInputConfig[$j]['notification_trigger']) {
                                                $notificationTriggerActive = 'checked="checked"';
                                            } else {
                                                $notificationTriggerInActive = 'checked="checked"';
                                            }
                                        } else {
                                            $name = 'Input' . $i;
                                            $notification_email = "";
                                            $activeLabelText = 'Active';
                                            $inactiveLabelText = 'Inactive';
                                            $enableNotification = '';
                                            $notificationTriggerActive = '';
                                            $notificationTriggerInActive = '';
                                        }
                                        ?>
                                        <tr>
                                            <td><input <?php echo $enableNotification; ?> name="ri_enable_ntfn_<?php echo $i; ?>" id="ri_enable_ntfn_<?php echo $i; ?>" type="checkbox" >
                                            <td><label id="ri_input_name_<?php echo $i; ?>"><?php echo $name; ?>11</label></td>
                                            <td class="ri_ntfn_trigger">
                                                <input type="radio" value="1" <?php echo $notificationTriggerActive ?> name="ri_ntfn_trigger_<?php echo $i; ?>" id="ri_ntfn_active_trigger_<?php echo $i; ?>">&nbsp;<label id="ri_active_label_<?php echo $i ?>"><?php echo $activeLabelText; ?></label> &nbsp;
                                                <input type="radio" value="0" <?php echo $notificationTriggerInActive ?>name="ri_ntfn_trigger_<?php echo $i; ?>" id="ri_ntfn_inactive_trigger_<?php echo $i; ?>">&nbsp;<label id="ri_inactive_label_<?php echo $i ?>"><?php echo $inactiveLabelText; ?></label>
                                            </td>
                                            <td><input type="text" value="<?php echo $notification_email;?>" id="ri_ntfn_mail_<?php echo $i; ?>" name="ri_ntfn_mail_<?php echo $i; ?>" /></td>
                                        </tr>
<?php endfor; ?>
                                </table>
                            </div>
                        </li>


                        <li>
                            <p style="padding-top: 88px;">In this section, we will configure Remotii outputs.</p>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%">
                                    <tr>
                                        <td>Enable</td>
                                        <td>Output Names</td>
                                        <td>Active Label</td>
                                        <td>Inactive Label</td>
                                    </tr>

<?php
for ($i = 1; $i <= 3; $i++):
    $j = $i - 1;
    if ($spOutputConfig[$j]['is_enabled']) {
        $checked = 'checked="checked"';
        $name = $spOutputConfig[$j]['name'];
        $activeLabelText = $spOutputConfig[$j]['active_label_text'];
        $activeLabelColor = $spOutputConfig[$j]['active_label_color'];
        $inactiveLabelText = $spOutputConfig[$j]['inactive_label_text'];
        $inactiveLabelColor = $spOutputConfig[$j]['inactive_label_color'];
        $isEnabled = $spOutputConfig[$j]['is_enabled'];
        $enableNotification = $spOutputConfig[$j]['enable_notification'];
        $notificationTrigger = $spOutputConfig[$j]['notification_trigger'];
        $disabled = '';
    } else {
        $checked = '';
        $name = '';
        $activeLabelText = '';
        $activeLabelColor = $greenColor;
        $inactiveLabelText = '';
        $inactiveLabelColor = $redColor;
        $isEnabled = '';
        $enableNotification = '';
        $notificationTrigger = '';
        $disabled = 'disabled="disabled"';
    }
    ?>

                                        <tr>
                                            <td><input <?php echo $checked; ?>type="checkbox" name="ro_enabled_<?php echo $i; ?>" id="ro_enabled_<?php echo $i; ?>" ></td>
                                            <td><input <?php echo $disabled; ?> type="text" name="ro_name_<?php echo $i ?>" id="ro_name_<?php echo $i ?>" placeholder="Output<?php echo $i; ?> Name" value="<?php echo $name; ?>"></td>
                                            <td>
                                                <input <?php echo $disabled; ?> type="text" name="ro_asl_<?php echo $i; ?>" id="ro_asl_<?php echo $i; ?>" placeholder="Active Label" value="<?php echo $activeLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $activeLabelColor ?>" name="ro_active_color_<?php echo $i; ?>"/>
                                                </div>
                                            </td>
                                            <td>
                                                <input <?php echo $disabled; ?> type="text" name="ro_iasl_<?php echo $i; ?>" id="ro_iasl_<?php echo $i; ?>" placeholder="Inactive Label" value="<?php echo $inactiveLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $inactiveLabelColor; ?>" name="ro_inactive_color_<?php echo $i; ?>"/>
                                                </div>
                                            </td>
                                        </tr>
<?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%">
                                    <tr>
                                        <th>Output Names</th>
                                        <th>Momentary</th> 
                                        <th colspan="2">Initial State</th>
                                    </tr>
<?php
for ($i = 1; $i <= 3; $i++):
    $j = $i - 1;
    if ($spOutputConfig[$j]['is_enabled']) {
        $name = $spOutputConfig[$j]['name'];
        $activeLabelText = $spOutputConfig[$j]['active_label_text'];
        $inactiveLabelText = $spOutputConfig[$j]['inactive_label_text'];

        if ($spOutputConfig[$j]['is_output_momentary']) {
            $isOutputMomentary = 'checked="checked"';
        } else {
            $isOutputMomentary = '';
        }
        $outputInitialStateActive = '';
        $outputInitialStateInactive = '';
        if ($spOutputConfig[$j]['output_initial_state']) {
            $outputInitialStateActive = 'checked="checked"';
        } else {
            $outputInitialStateInactive = 'checked="checked"';
        }
    } else {
        $name = 'Output' . $i;
        $activeLabelText = 'Active';
        $inactiveLabelText = 'Inactive';
        $outputInitialStateActive = '';
        $outputInitialStateInactive = '';
    }
    ?>
                                        <tr>
                                            <td> <label id="ro_step2_name_<?php echo $i; ?>"><?php echo $name; ?></label> </td>
                                            <td><input type="checkbox" <?php echo $isOutputMomentary ?>name="ro_momentary_<?php echo $i; ?>" id="ro_momentary_<?php echo $i; ?>"></td>
                                            <td>
                                                <input type="radio" value="1" <?php echo $outputInitialStateActive; ?> id="ro_active_initialState_<?php echo $i; ?>" name="ro_initialState_<?php echo $i; ?>">&nbsp;<label id="ro_step2_active_label_<?php echo $i; ?>"><?php echo $activeLabelText ?> </label>&nbsp;&nbsp;
                                                <input type="radio" value="0" <?php echo $outputInitialStateInactive; ?> id="ro_inactive_initialState_<?php echo $i; ?>" name="ro_initialState_<?php echo $i; ?>">&nbsp;<label id="ro_step2_inactive_label_<?php echo $i; ?>"><?php echo $inactiveLabelText; ?></label>
                                            </td>
                                        </tr>
<?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%">
                                    <tr>
                                        <th>Enable notifications</th>
                                        <th>Output Names</th> 
                                       <!--  <th>Notification Trigger</th> -->
                                    </tr>
<?php
for ($i = 1; $i <= 3; $i++):
    $j = $i - 1;
    if ($spOutputConfig[$j]['is_enabled']) {
        $name = $spOutputConfig[$j]['name'];
        $activeLabelText = $spOutputConfig[$j]['active_label_text'];
        $inactiveLabelText = $spOutputConfig[$j]['inactive_label_text'];
        if ($spOutputConfig[$j]['enable_notification']) {
            $enableNotification = 'checked="checked"';
        } else {
            $enableNotification = '';
        }

        $notificationTriggerActive = '';
        $notificationTriggerInActive = '';
        if ($spOutputConfig[$j]['notification_trigger']) {
            $notificationTriggerActive = 'checked="checked"';
        } else {
            $notificationTriggerInActive = 'checked="checked"';
        }
    } else {
        $name = 'Output' . $i;
        $activeLabelText = 'Active';
        $inactiveLabelText = 'Inactive';
        $enableNotification = '';
        $notificationTriggerActive = '';
        $notificationTriggerInActive = '';
    }
    ?>
                                        <tr>
                                            <td><input <?php echo $enableNotification ?> name="ro_enable_ntfn_<?php echo $i; ?>" id="ro_enable_ntfn_<?php echo $i; ?>" type="checkbox" ></td>
                                            <td><label id="ro_input_name_<?php echo $i; ?>"><?php echo $name; ?></label></td>
                                            <!-- <td class="ro_ntfn_trigger">
                                                <input type="radio" <?php //echo $notificationTriggerActive; ?> name="ro_ntfn_trigger_<?php //echo $i; ?>" id="ro_ntfn_active_trigger_<?php //echo $i; ?>" value='1'>&nbsp;<label id="ro_active_label_<?php //echo $i ?>"><?php //echo $activeLabelText; ?></label> &nbsp;
                                                <input type="radio" <?php //echo $notificationTriggerInActive; ?> name="ro_ntfn_trigger_<?php //echo $i; ?>" id="ro_ntfn_inactive_trigger_<?php //echo $i; ?>" value='0'>&nbsp;<label id="ro_inactive_label_<?php //echo $i ?>"><?php //echo $inactiveLabelText; ?></label>
                                            </td> -->
                                        </tr>
<?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div id="msg_tpl_1" style="padding-top: 100px;">
                                <p>We’re are all done. Thanks to set a default Remotii setup for your users.</p>
                                <p><a href="#" class="btn2" onclick="return setupRemotii();">Finish</a></p>
                            </div>
                            <div id="setup_finish" style="padding-top: 160px;display:none;"></div>
                        </li>

                    </ul>
                </div>
            </div>

        </form>

        <script type="text/javascript" src="<?php echo BASE_URL . '/assets/c/js/spin.js' ?>"></script>
        <script>

            function setupRemotii()
            {
                target = document.getElementById('setup_finish');
                opts.top = -125;
                var spinner = new Spinner(opts);

                $("#msg_tpl_1").hide();
                $("#setup_finish").html('<span style="font-size:20px;">Setting up remotii....<span>');
                $("#setup_finish").show();
                spinner.spin(target);

                var form_serialized_data = $("#form_default_remotii_setup").serialize();

                //alert(form_serialized_data);

                jQuery.ajax({
                    url: '<?php print BASE_URL . '/client/custom-remotii-setup/'.$remotiiId; ?>',
                    type: 'post',
                    async: false,
                    data: form_serialized_data,
                    success: function(response) {
                        console.log(response);
                        spinner.stop(target);
                        $("#setup_finish").html('<span style="color:green;font-size:14px;">Default Remotii has been setup successfully.</span>');
                        window.top.location.href = "<?php print BASE_URL . '/client/my-remotii'; ?>";
                    },
                    /*complete:function(response){
                     console.log( data );
                     }*/
                });
            }

            var opts = {
                lines: 13, // The number of lines to draw
                length: 20, // The length of each line
                width: 10, // The line thickness
                radius: 30, // The radius of the inner circle
                corners: 1, // Corner roundness (0..1)
                rotate: 0, // The rotation offset
                direction: 1, // 1: clockwise, -1: counterclockwise
                color: '#000', // #rgb or #rrggbb or array of colors
                speed: 1, // Rounds per second
                trail: 60, // Afterglow percentage
                shadow: false, // Whether to render a shadow
                hwaccel: false, // Whether to use hardware acceleration
                className: 'spinner', // The CSS class to assign to the spinner
                zIndex: 2e9, // The z-index (defaults to 2000000000)
                top: 'auto', // Top position relative to parent in px
                left: 'auto' // Left position relative to parent in px
            };
        </script>
    </body>
</html>