<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Remotii Enduser</title>
        <?php $baseUrl = BASE_URL . "/assets/f"; ?>
        <link href="<?php echo $baseUrl; ?>/css/reset.css" type="text/css" rel="stylesheet">
        <link href="<?php echo $baseUrl; ?>/css/main.css" type="text/css" rel="stylesheet" charset="utf-8">
        <?php echo $this->headLink()->appendStylesheet($baseUrl . '/css/main-phase2.css'); ?>
        <link href="<?php echo $baseUrl; ?>/css/main-phase2.css" type="text/css" rel="stylesheet" charset="utf-8">
        <link href="<?php echo $baseUrl; ?>/css/buttons.css" type="text/css" rel="stylesheet" charset="utf-8">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
        <link href="<?php echo $baseUrl; ?>/css/screen.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?php echo $baseUrl; ?>/css/colorbox.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?php echo $baseUrl; ?>/css/jquery-ui.css" rel="stylesheet" type="text/css" media="screen" />
        <script src="<?php echo $baseUrl; ?>/js/jquery-1.7.1.min.js" type="text/javascript"></script>
        <script src="<?php echo $baseUrl; ?>/js/jquery-ui.js" type="text/javascript"></script>
        <script  type="text/javascript" src="<?php echo $baseUrl; ?>/js/custom.js"></script>
        <script type="text/javascript" src="<?php echo $baseUrl; ?>/js/easySlider1.7.js"></script>
        <!--<script type="text/javascript" src="<?php echo $baseUrl; ?>/assets/b/js/jquery.colorbox.js"></script>-->

        <script type="text/javascript">

            $(document).ready(function() {
                $("#slider ul li").css({width: '750px', height: '420px'});
                $("#slider").easySlider({controlsShow: false});


                $('.check').change(function() {
                    if ($(this).is(":checked")) {
                        $(this).parent('td').siblings().find('.radio').removeAttr('disabled');
                        $(this).parent('td').siblings().find('.r1').attr("checked", "checked");
                    }
                    else {
                        $(this).parent('td').siblings().find('.radio').attr('disabled', 'disabled');
                        $(this).parent('td').siblings().find('.r1').removeAttr("checked", "checked");
                    }
                });


                //  $('.radio').disabled;
                $(function() {
                    $(".datepicker").datepicker({minDate: 0,
                        showOn: "button",
                        buttonImage: "<?php echo $baseUrl . "/images/calendar.png"; ?>",
                        buttonImageOnly: true
                    });
                });

            });
        </script>
        <script type="text/javascript">
            // JavaScript Document
            $(document).ready(function() {
                $('.delrow').click(function() {
                    var id = $(this).attr('value');
                    var $ele = $(this).parent().parent();

                    if (confirm("Are you sure you want to delete this event?")) {
                        $.post("<?php echo BASE_URL . "/client/iajax"; ?>",
                                {
                                    action: "delete",
                                    params: {
                                        iddel: id
                                    }
                                }
                        ,
                                function(data) {

                                    if (data == true) {
                                        $ele.remove();
//                                    location.reload();
                                    } else {
                                        alert("can't delete the row")
                                        $('#response').attr("class", "error m0");
                                        $('#response').html(data.result);
                                    }
                                }, 'json');
                    }
                });
                $('.active').click(function() {
                    var val = null;
                    var up_id = $(this).attr('id');
                    var values = $(this).attr('data');

                    if (values == 0) {
                        val = 1;

                    } else {

                        val = 0;
                    }

                    $.post("<?php echo BASE_URL . "/client/iajax"; ?>",
                            {
                                action: "active",
                                params: {
                                    value: val,
                                    id: up_id
                                }
                            }
                    ,
                            function(data) {
                                console.log(data);
                                if (data.status == "success") {

                                    window.location.reload();
                                }
                                else {
                                    alert(data.result);
                                }
                            },
                            "json");
                });
                // Time and Repetition
                $(".onceSec").show();
                $(".frequency").change(function() {

                    var val = $(this).val();
//	console.log($(this).val());
                    if (val == "0")
                    {
                        $(".timingSet").hide();
                        $(".onceSec").show();
//                      
                        //alert($date);
                    }
                    if (val == "1")
                    {
                        $(".timingSet").hide();
                        $(".everydaySec").show();
                    }
                    if (val == "2")
                    {
                        $(".timingSet").hide();
                        $(".daySec").show();
                    }
                    if (val == "3")
                    {
                        $(".timingSet").hide();
                        $(".monthlySec").show();
                    }
                    if (val == "4")
                    {
                        $(".timingSet").hide();
                        $(".yearlySec").show();
                    }
                });
                $(".datepicker").change(function() {
                    var inp = $(this);
                    if (inp.val() != 'NULL') {
                        $(this).parent('p').find('#lable').text('');
                    }
                });
                $(".days").change(function() {
                    var inp = $(this);
                    if (inp.val() != 'NULL') {
                        $(this).find('#lable1').text('');
                    }
                });
                $(".save").click(function() {

                    if ($(this).parent('div').siblings().siblings().find('.t1').find('.sel').val() == 0) {
                        if ($(this).parent('div').siblings().find('.datepicker').val() == '') {
                            $(this).parent('div').siblings().find('#lable').css('display', 'inline-block');
                            return false;
                        }
                    }
                    else if ($(this).parent('div').siblings().siblings().find('.t1').find('.sel').val() == 2) {
                        if ($(this).parent('div').siblings().find('input[name="days[]"]:checked').length == 0) {
                            $(this).parent('div').siblings().find('#lable1').css('display', 'inline-block');
                            return false;
                        }
                    }
                    if ($(this).parent('div').siblings('.table').find('#check1').is(':checked')) {
                        return true;
                    }
                    else {
                        alert("Atleast one output pin should be selected");
                        return false;
                    }
                });
                $(".monthchange").change(function() {
                    var value = $(this).val();

                    if (value == 3 || value == 5 || value == 7 || value == 8 || value == 10 || value == 12) {
                        num = 31;
                        month1(num);
                    }
                    else if (value == 2 || value == 4 || value == 6 || value == 9 || value == 11) {
                        num = 30;
                        month1(num);
                    }
                });

                function month1(num) {
                    $('.datechange').html("");
                    for (i = 1; i <= num; i++) {
                        $('.datechange').append("<option value=" + i + ">" + i + "</option>");
                    }
                }


            });

        </script>

    </head>
    <?php
    $form = $this->form;

    $form->prepare();

    $form->setAttribute('action', $this->url('remotiifrontend', array(
                'action' => 'event-scheduler',
                'id' => $this->rid,
    )));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <?php if (!empty($response)) { ?>
        <span class="<?php echo $response['status']; ?> form_response"><?php echo $response['message']; ?></span>
    <?php } ?>
    <body>
        <div class="remotii-setup modify scheduler">
            <div id="slider">
                <ul>
                    <li>
                        <h2>Scheduler Summary - <span><?php echo $remotiiMacData[0]['remotii_name']; ?></span></h2>
                        <div class="form rinput  add-event-wrap">
                            <table width="100%" cellspacing="0" cellpadding="0">
                                <tr>
                                     <th width="130">Event Name</th>
                                    <th width="160">Trigger on</th>
                                   
                                    <th width="110">Time</th>
                                    <th width="130">Schedule</th>
                                    <th width="110">Status</th>
                                    <th width="130">Actions</th>
                                </tr>
                                <?php
                                foreach ($data as $value) {
                                    if ($value['occurence_type'] == "0") {
                                        ?>
                                        <tr class="tr"> 
<td><?php echo $value['event_name']; ?></td>
                                            <td> <?php echo $value['occurence_date'] . "-" . $monthName = date("M", mktime(0, 0, 0, $value['occurence_month'], 10)) . "-" . $value['occurence_year']; ?> </td>
                                           
                                           <td><?php echo $value['occurence_time']; ?></td>
                                            <td><?php echo Once; ?></td>

                                            <td><?php
                                                if ($value['event_status'] == 1) {

                                                    echo Enabled;
                                                } else {

                                                    echo Disabled;
                                                }
                                                ?></td>
                                            <td><a href="<?php echo $this->url('remotiifrontend', array('action' => 'event-scheduler-edit', 'id' => $value['id'])); ?>" class="next-slide-btn3"><img src="<?php echo $baseUrl . "/images/edit-icon.png"; ?>" title="Edit"></a>
                                                <a href="javascript:void(0);" class="mlr5 active"  data="<?php echo $value['event_status'] ?>"
                                                   id="<?php echo $value['id'] ?>">         
                                                       <?php if ($value['event_status'] == 1) { ?>

                                                        <img src="<?php echo $baseUrl . "/images/enable.png"; ?>" title="Disable">
                                                    <?php } else { ?>

                                                        <img src="<?php echo $baseUrl . "/images/right.png"; ?>" title="Enable">
                                                    <?php }
                                                    ?></a> 

                                                <input type="hidden" id="id" val>
                                                <a href="javascript:void(0);"  class=" delrow" post="<?php echo $post; ?>" value="<?php echo $value['id']; ?>" ><img src="<?php echo $baseUrl . "/images/delete-icon.png"; ?>" title="Delete"></a>

                                            </td>
                                        </tr>
                                    <?php } elseif ($value['occurence_type'] == "1") {
                                        ?>
                                        <tr> 
                                             <td><?php echo $value['event_name']; ?></td>
                                            <td> <?php echo 'Everyday' ?> </td>
                                           
                                            <td><?php echo $value['occurence_time']; ?></td>
                                            <td><?php echo 'Everyday'; ?></td>

                                            <td><?php
                                                if ($value['event_status'] == 1) {

                                                    echo Enabled;
                                                } else {

                                                    echo Disabled;
                                                }
                                                ?></td>
                                            <td><a href="<?php echo $this->url('remotiifrontend', array('action' => 'event-scheduler-edit', 'id' => $value['id'])); ?>" class="next-slide-btn3"><img src="<?php echo $baseUrl . "/images/edit-icon.png"; ?>" title="Edit"></a>
                                                <a href="javascript:void(0);" class="mlr5 active"  data="<?php echo $value['event_status'] ?>"
                                                   id="<?php echo $value['id'] ?>">         
                                                       <?php if ($value['event_status'] == 1) { ?>

                                                        <img src="<?php echo $baseUrl . "/images/enable.png"; ?>" title="Disable">
                                                    <?php } else { ?>

                                                        <img src="<?php echo $baseUrl . "/images/right.png"; ?>" title="Enable">
                                                    <?php }
                                                    ?></a> 
                                                <input type="hidden" id="id" val>
                                                <a href="javascript:void(0);" class=" delrow" value="<?php echo $value['id']; ?>" ><img src="<?php echo $baseUrl . "/images/delete-icon.png"; ?>" title="Delete"></a>
                                            </td>
                                        </tr>
                                        <?php
                                    } elseif ($value['occurence_type'] == "2") {
                                        ?>
                                        <tr> 
                                               <td><?php echo $value['event_name']; ?></td>
                                            <td> <?php echo $value['occurence_days'].' '; ?> </td>
                                         
                                            <td><?php echo $value['occurence_time']; ?></td>
                                            <td><?php echo "Set Of Days" ?></td>

                                            <td><?php
                                                if ($value['event_status'] == 1) {

                                                    echo Enabled;
                                                } else {

                                                    echo Disabled;
                                                }
                                                ?></td>
                                            <td><a href="<?php echo $this->url('remotiifrontend', array('action' => 'event-scheduler-edit', 'id' => $value['id'])); ?>" class="next-slide-btn3"><img src="<?php echo $baseUrl . "/images/edit-icon.png"; ?>" title="Edit"></a>
                                                <a href="javascript:void(0);" class="mlr5 active"  data="<?php echo $value['event_status'] ?>"
                                                   id="<?php echo $value['id'] ?>">         
                                                       <?php if ($value['event_status'] == 1) { ?>

                                                        <img src="<?php echo $baseUrl . "/images/enable.png"; ?>" title="Disable">
                                                    <?php } else { ?>

                                                        <img src="<?php echo $baseUrl . "/images/right.png"; ?>" title="Enable">
                                                    <?php }
                                                    ?></a> 
                                                <input type="hidden" id="id" val>
                                                <a href="javascript:void(0);"  class=" delrow" value="<?php echo $value['id']; ?>" ><img src="<?php echo $baseUrl . "/images/delete-icon.png"; ?>" title="Delete"></a>
                                            </td>
                                        </tr>
                                        <?php
                                    } elseif ($value['occurence_type'] == "3") {
                                        ?>
                                        <tr> 
                                             <td><?php echo $value['event_name']; ?></td>
                                            <td> <?php
                                                if ($value['occurence_date'] == 1 || $value['occurence_date'] == 31 || $value['occurence_date'] == 21) {
                                                    echo $value['occurence_date'] . 'st' . " " . 'of every month';
                                                } elseif ($value['occurence_date'] == 2 || $value['occurence_date'] == 22) {
                                                    echo $value['occurence_date'] . 'nd' . " " . 'of every month';
                                                } elseif ($value['occurence_date'] == 3 || $value['occurence_date'] == 23) {
                                                    echo $value['occurence_date'] . 'rd' . " " . 'of every month';
                                                } else {
                                                    echo $value['occurence_date'] . 'th' . " " . 'of every month';
                                                }
                                                ?> </td>
                                           
                                            <td><?php echo $value['occurence_time']; ?></td>
                                            <td><?php echo Monthly ?></td>

                                            <td><?php
                                                if ($value['event_status'] == 1) {

                                                    echo Enabled;
                                                } else {

                                                    echo Disabled;
                                                }
                                                ?></td>                                           
                                            <td><a href="<?php echo $this->url('remotiifrontend', array('action' => 'event-scheduler-edit', 'id' => $value['id'])); ?>" class="next-slide-btn3"><img src="<?php echo $baseUrl . "/images/edit-icon.png"; ?>" title="Edit"></a>
                                                <a href="javascript:void(0);" class="mlr5 active"  data="<?php echo $value['event_status'] ?>"
                                                   id="<?php echo $value['id'] ?>">         
                                                       <?php if ($value['event_status'] == 1) { ?>

                                                        <img src="<?php echo $baseUrl . "/images/enable.png"; ?>" title="Disable">
                                                    <?php } else { ?>

                                                        <img src="<?php echo $baseUrl . "/images/right.png"; ?>" title="Enable">
                                                    <?php }
                                                    ?></a> 
                                                <input type="hidden" id="id" val>
                                                <a href="javascript:void(0);" class=" delrow" value="<?php echo $value['id']; ?>" ><img src="<?php echo $baseUrl . "/images/delete-icon.png"; ?>" title="Delete"></a>
                                            </td>
                                        </tr>
                                        <?php
                                    } elseif ($value['occurence_type'] == "4") {
                                        ?>
                                        <tr> 
                                               <td><?php echo $value['event_name']; ?></td>
                                            <td>
                                                <span> <?php
                                                    if ($value['occurence_date'] == 1 || $value['occurence_date'] == 31 || $value['occurence_date'] == 21)
                                                        echo $value['occurence_date'] . 'st' . " ";
                                                    elseif ($value['occurence_date'] == 2 || $value['occurence_date'] == 22)
                                                        echo $value['occurence_date'] . 'nd' . " ";
                                                    elseif ($value['occurence_date'] == 3 || $value['occurence_date'] == 23)
                                                        echo $value['occurence_date'] . 'rd' . " ";
                                                    else
                                                        echo $value['occurence_date'] . 'th' . " ";
                                                    ?>
                                                    <?php
                                                    if ($value['occurence_month'] == 1)
                                                        echo 'Jan' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 2)
                                                        echo 'Feb' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 3)
                                                        echo 'Mar' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 4)
                                                        echo 'Apr' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 5)
                                                        echo 'May' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 6)
                                                        echo 'June' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 7)
                                                        echo 'July' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 8)
                                                        echo 'Aug' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 9)
                                                        echo 'Sep' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 10)
                                                        echo 'Oct' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 11)
                                                        echo 'Nov' . " " . 'of every year';
                                                    elseif ($value['occurence_month'] == 12)
                                                        echo 'Dec' . " " . 'of every year';
                                                    ?>
                                                </span </td>
                                         
                                            <td><?php echo $value['occurence_time']; ?></td>
                                            <td><?php echo Yearly ?></td>

                                            <td><?php
                                                if ($value['event_status'] == 1) {

                                                    echo Enabled;
                                                } else {

                                                    echo Disabled;
                                                }
                                                ?></td>
                                            <td><a href="<?php echo $this->url('remotiifrontend', array('action' => 'event-scheduler-edit', 'id' => $value['id'])); ?>" class="next-slide-btn3"><img src="<?php echo $baseUrl . "/images/edit-icon.png"; ?>" title="Edit"></a>
                                                <a href="javascript:void(0);" class="mlr5 active"  data="<?php echo $value['event_status'] ?>"
                                                   id="<?php echo $value['id'] ?>">         
                                                       <?php if ($value['event_status'] == 1) { ?>

                                                        <img src="<?php echo $baseUrl . "/images/enable.png"; ?>" title="Disable">
                                                    <?php } else { ?>

                                                        <img src="<?php echo $baseUrl . "/images/right.png"; ?>" title="Enable">
                                                    <?php }
                                                    ?></a>  
                                                <input type="hidden" id="id" val>
                                                <a href="javascript:void(0);" class=" delrow" value="<?php echo $value['id']; ?>" ><img src="<?php echo $baseUrl . "/images/delete-icon.png"; ?>" title="Delete"></a>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </table>
                            <br>

                        </div>
                        <a href="javascript:void(0);" class="btn2 add-event next-slide-btn">Add Event</a>
                    </li>
                    <li>
                        <h2>Warning</h2>
                        <div class="warning">
                            <p>
                                I hereby agree to the Remotii terms of service and understand that by using the Remotii Event Scheduler, I am requesting the Remotii server system to generate a controlling event for my Remotii, on my behalf, that may modify the output state of the selected Remotii and any equipment that it may be connected to.  

                                I  <br>further acknowledge that the fulfillment of the controlling event request is on a best effort basis and cannot be 100% guaranteed to take place or execute precisely on time.  I understand that any event that cannot be scheduled within a 5 minute window shall be discarded and the state of my Remotii and its connected equipment shall remain unchanged.
                            </p>

                        </div>
                        <div class="al"><a href="javascript:void(0);" class="btn3  next-slide-btn">I Agree</a> <a href="javascript:void(0);" class="btn2 prev-slide-btn" >Cancel</a></div>
                    </li>
                    <li>
                        <h2>Add New Event - <span><?php echo ($remotiiMacData[0]['remotii_name']); ?></span></h2>
                        <div class="timimg">
                              <p class="t"> <label>Event Name: </label> <input type="text" name="event_name" class="small"></p>
                            <h3 class="m0">Output</h3>
                        </div>
                        <table width="100%" cellspacing="0" class="table">
                            <?php
                            $i = 0;
                            foreach ($OutputConfig as $outputconfig) {
                                ?>
                                <tr>
                                    <td>
                                        <input type="hidden" name="pin_output_config_id[<?php echo $outputconfig['config_id'] ?>]" value="<?php echo $outputconfig[pin_number] ?>">
                                        <input type="hidden" name="pin_number[]" value="<?php echo $outputconfig[pin_number] ?>">
                                        <input type="hidden" name="IsMomentary[<?php echo $outputconfig['config_id'] ?>]" value="<?php echo $outputconfig[is_output_momentary] ?>">


                                        <?php
                                        $form->get('outputname[]')->setCheckedValue($outputconfig['config_id']);
                                        if ($outputconfig[is_output_momentary] == 1) {
                                            ?>
                                            <?php echo $this->formRow($form->get('outputname[]')); ?><span> <?php echo $outputconfig['name'] . ' ' . '(Momentary)'; ?></span>


                                            <?php
                                        } else {
                                            echo $this->formRow($form->get('outputname[]'));
                                            ?><span> <?php
                                                echo $outputconfig['name'];
                                            }
                                            ?></span>


                                    <td>
                                        <div class="colorbox" style="background:<?php echo $outputconfig['active_label_color'] ?>" ></div>

                                        <?php if ($outputconfig[is_output_momentary] == 0) { ?> <input type="radio" class ="radio r1"  name="radioState[<?php echo $outputconfig['config_id'] ?>]" value="1"  disabled  > <?php } ?>

                                        <?php echo $outputconfig['active_label_text'] ?>
                                    </td>
                                    <td>
                                        <div class="colorbox " style="background:<?php echo $outputconfig['inactive_label_color'] ?>" ></div>

                                        <?php if ($outputconfig[is_output_momentary] == 0) { ?> <input type="radio" class ="radio" name="radioState[<?php echo $outputconfig['config_id'] ?>]" value="0" disabled> <?php } ?>
                                        <?php echo $outputconfig['inactive_label_text'] ?>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            }
                            ?>
                        </table>
                     
                        <div class="timimg">
                            <h3>Time and Repetition</h3>
                          
                            <p class="t">
                                <label>Time : </label>
                                <select class="timing"  name="hours">

                                    <option value="01">01</option>
                                    <option value="02">02</option>
                                    <option value="03">03</option>
                                    <option value="04">04</option>
                                    <option value="05">05</option>
                                    <option value="06">06</option>
                                    <option value="07">07</option>
                                    <option value="08">08</option>
                                    <option value="09">09</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>                      
                                <select class="timing" name=" min">

                                    <?php for ($i = 0; $i <= 59; $i++) { ?>

                                        <option value="<?php echo $i; ?>"><?php
                                            if ($i <= 9)
                                                echo '0' . $i;
                                            elseif ($i > 9)
                                                echo $i;
                                            ?></option>

                                    <?php } ?>
                                </select>
                                <select class="timing"  name="am">
                                    <option value="AM">AM</option>
                                    <option value="PM">PM</option>                           
                                </select><br>
                            </p>
                            <p class="t t1">
                                <!--input type="text" value="11:30 AM" id="basicExample"--> 
                                <label>Frequency : </label>  
                                <select class="frequency sel" name="occurence_type">
                                    <option value="0">Once</option>
                                    <option value="1">Everyday</option>
                                    <option value="2">Set Of Days</option>
                                    <option value="3">Monthly</option>
                                    <option value="4">Yearly</option>
                                </select></p>
                            <p class="timingSet onceSec t"><label>Date : </label><input type="text" class="datepicker" name="occurence_date"></input>
                                <span id="lable" style="display: none; color:red; font-size: 10pt">Cannot be empty</span>
                            </p> 


<!--                            <p>
           <input type="text" value="11:30 AM" name="occurence_time" id="basicExample" class="ui-timepicker-input" autocomplete="off"> -->


                            <p class="timingSet daySec days">


                                <input type="checkbox" class="check1" name="days[]" value="Mon"> <span>Monday</span>
                                <input type="checkbox" class="check1" name="days[]" value="Tue"> <span>Tuesday</span>
                                <input type="checkbox" class="check1" name="days[]" value="Wed"> <span>Wednesday</span>
                                <input type="checkbox"  class="check1" name="days[]" value="Thu"> <span>Thursday</span>
                                <input type="checkbox"  class="check1" name="days[]" value="Fri"> <span>Friday</span>
                                <input type="checkbox" class="check1" name="days[]" value="Sat"> <span>Saturday</span>
                                <input type="checkbox"  class="check1" name="days[]" value="Sun"> <span>Sunday</span>

                                <span id="lable1" style="display: none; color:red; font-size: 10pt">Select atleast one</span></p>
                            <p class="timingSet monthlySec  t"> <label>Date : </label> 
                                <select name="date1" class="d">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                    <option value="13">13</option>
                                    <option value="14">14</option>
                                    <option value="15">15</option>
                                    <option value="16">16</option>
                                    <option value="17">17</option>
                                    <option value="18">18</option>
                                    <option value="19">19</option>
                                    <option value="20">20</option>
                                    <option value="21">21</option>
                                    <option value="22">22</option>
                                    <option value="23">23</option>
                                    <option value="24">24</option>
                                    <option value="25">25</option>
                                    <option value="26">26</option>
                                    <option value="27">27</option>
                                    <option value="28">28</option>
                                    <option value="29">29</option>
                                    <option value="30">30</option>
                                    <option value="31">31</option>
                                </select></p>
                            <p class="timingSet yearlySec t">
                                <span class="ml10">Date : </span> 
                                <select name="date" class="datechange d">
                                    <?php for ($i = 1; $i <= 31; $i++) { ?><option value="<?php echo $i ?>"><?php echo $i; ?></option><?php } ?>

                                </select>
                                <span class="mon">Month : </span> 
                                <select name="month" class="monthchange m">
                                    <option value="1">Jan</option>
                                    <option value="2">Feb</option>
                                    <option value="3">Mar</option>
                                    <option value="4">Apr</option>
                                    <option value="5">May</option>
                                    <option value="6">June</option>
                                    <option value="7">July</option>
                                    <option value="8">Aug</option>
                                    <option value="9">Sept</option>
                                    <option value="10">Oct</option>
                                    <option value="11">Nov</option>
                                    <option value="12">Dec</option></select>

                            </p>

                        </div>


                        <div class="alL">
                            <?php echo $this->formSubmit($form->get('save')); ?>  <a href="javascript:void(0);" class="btn2 next-slide-btn">Set Input Condition</a></div>
                    </li>
                    <li>
                        <h2>Set Input Status Conditions</h2>
                        <div class="inputStatus">
                            <span>When</span>
                            <select name="condition_type">
                                <option value="0">Any</option>
                                <option value="1">All</option>
                            </select>
                            <span>of the following input conditions met</span>
                            <table width="100%" cellspacing="0">
                                <?php
                                $i = 0;
                                foreach ($InputConfig as $inputconfig) {
                                    ?>
                                    <tr>
                                        <td> 
                                            <input type="hidden" name="pin_input_config_id[<?php echo $inputconfig['config_id'] ?>]" value="<?php echo $inputconfig[pin_number] ?>">
                                            <input type="hidden" name="pin_number1[]" value="<?php echo $inputconfig[pin_number] ?>">
                                            <?php
                                            $form->get('inputname[]')->setCheckedValue($inputconfig['config_id']);
                                            echo $this->formRow($form->get('inputname[]'));
                                            ?> 
                                            <span><?php echo $inputconfig['name']; ?></span>
                                        </td>
                                        <td>
                                            <div class="colorbox"
                                                 style="background:<?php echo $inputconfig['active_label_color'] ?>" >
                                            </div>
                                            <input type="radio" class="radio r1" name="radio1[<?php echo $inputconfig['config_id'] ?>]" value="1"  disabled><?php echo $inputconfig['active_label_text']; ?>
                                        </td>
                                        <td>
                                            <div class="colorbox" style="background:<?php echo $inputconfig['inactive_label_color'] ?>" ></div>
                                            <input type="radio"  class="radio" name="radio1[<?php echo $inputconfig['config_id'] ?>]" disabled value="0" ><?php echo $inputconfig['inactive_label_text']; ?>
                                        </td>
                                    </tr><?php
                                    $i++;
                                }
                                ?>

                                <input type="hidden" name="remotii_id" value="<?php echo $this->rid ?>">
                                <input type="hidden" name="mac_address" value="<?php echo $remotiiMacData[0]['mac_address'] ?>">



                            </table>
                            <br>
                            <a href="javascript:void(0);" class=" btn2 prev-slide-btn" >Back</a>
                            <a href="javascript:void(0);" class=" btn3 prev-slide-btn" >&nbsp;Set&nbsp;</a>


                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </body>
