<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">   
    <h2>Getting Started</h2>
  </div>
</div>
<!-- Tag line ends --> 
<div class="content" style="overflow: hidden;">

<div class="wrapper page-con">
	<h3 class="heading3">Video Tutorials</h3>
	<p>Watch Professor Remotii setup his Remotii in a variety of different scenarios.</p>
	<div class="img-wrap">   
            <p class="left"><iframe width="490" height="398" src="https://www.youtube.com/embed/JHy9TV-m0es" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>
            <p class="right"><iframe width="490" height="398" src="https://www.youtube.com/embed/qRa_qtFa7RY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>

            <div style="float:left; width: 100%;"></div>
            <p class="left"><iframe width="490" height="398" src="https://www.youtube.com/embed/uBcu1r5Jeds" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>
            <p class="right"><iframe width="490" height="398" src="https://www.youtube.com/embed/EvYeqGtO3W0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>            

            <div style="float:left; width: 100%;"></div>
            <p class="left"><iframe width="490" height="398" src="https://www.youtube.com/embed/ilwD1Qq5a7M" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>
            <p class="right"><iframe width="490" height="398" src="https://www.youtube.com/embed/c07UR6d7DHw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></p>            
    </div>    
</div>

<div class="wrapper page-con">
	<h3 class="heading3">Wiring Diagrams</h3>
	<p>There are a lot of things you can do with your Remotii.  Please find below an illustration showing your Remotii's basic connections.</p>
	<div class="img-wrap">
            
            <p class="left"><img alt="" src="<?php echo BASE_URL?>/assets/f/images/remotii-diagram-alarm2bdrw.jpg" width=490 height=398></p>
            <p class="right"><img alt="" src="<?php echo BASE_URL?>/assets/f/images/remotii-diagram-switchb.jpg" width=490 height=398></p>
            
            <div style="float:left; width: 100%;"></div>
            <p class="left"><img alt="" src="<?php echo BASE_URL?>/assets/f/images/remotii-diagram-FIRE-PANELb.jpg" width=490 height=398></p>
            <p class="right"><img alt="" src="<?php echo BASE_URL?>/assets/f/images/remotii-diagram-wirlessab" width=490 height=398></p>
    </div>
</div>

<div class="wrapper page-con">    
    <h3 class="heading3">Offline Documentation</h3>
    <div style="float:left; width: 100%;"></div>     
    <div class="img-wrap">
        <div width="490" height="398">
            <p class="left">Click <a href="<?php echo BASE_URL?>/assets/f/documents/remotii-quick-start-guide.pdf">here</a> to download the Remotii Quick Start Guide</p>
        </div>
    </div>
</div>

</div>
<!--/content-->