<?php
$title = 'Register Remotii Service Provider';
$this->headTitle($title);
?>
<!-- Tag line  -->
<div class="tag-line">
    <div class="wrapper">   
        <h2>Become An RSP</h2>
    </div>
</div>
<!-- Tag line ends --> 
<div class="wrapper page-con">	
	<h3 class="heading3">Resell Remotii as a Remotii Service Provider.</h3>

  <ul class="list3">
    <li>
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Customer-Retention.png" alt=""></div>
      <div class="con">
        <h4>Customer Retention </h4>
        <p>Remotii can help retain your customers. Technology is always changing, but there are still plenty of great products available that would be BETTER with Internet connectivity.  Remotii allows you to add Internet connectivity to things your customers have already purchased. Adding remote control and monitoring to existing devices often costs less than device replacement and create new ways to enhance your customer's IOT experience while also increasing your revenue.</p>
      </div>      
    </li>
    
    <li>            
      <div class="con">
        <h4>Initial Investment</h4>
        <p>Remotii's have great mark-up potential and are easily sold for 30% to 100% over their RSP purchase rate. Remotii Inc. offers great bulk quantity discounts.</a>
      </div>  
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Initial-investment.png" alt=""></div>      
    </li>    
    
    <li>      
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Minimums.png" alt=""></div>        
      <div class="con">
        <h4>Minimums</h4>
        <p>In order to become an RSP, you must sign-up for an RSP account and place an order for 5 Remotii's.</p>
      </div>        
    </li> 
    
    <li>      
      <div class="con">
        <h4>Monthly Payments</h4>
        <p>As a Remotii Service Provider, you choose the monthly service rate for each Remotii sold by your organization.  Your RSP delivers Remotii Inc. $3/month for each activated Remotii on your RSP account.  Typical reseller service rates range between $8/month to $20/month depending on the service industry.  The difference is your to keep.</p>
      </div>      
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Monthly Payments.png" alt=""></div>
    </li>    
   
    <li>      
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Fast-setup.png" alt=""></div>                  
      <div class="con">
        <h4>Fast Setup</h4>
        <p>Remotii understands that your time is valuable.  You can pre-configure your customer's device before it's installed.  Your RSP account provides the ability to preconfigure new devices by copying configuration settings from other similar setups, or by inheriting settings from your RSP default template.  Additional personalization may be made any time prior to device installation.</p>
      </div>        
    </li>   
    
    <li>            
      <div class="con">
        <h4>End User Billing</h4>
        <p>Many of our RSPs have been in business for a long time and already have an end-user billing system in place.  If you already have a billing system in place, and you like it, then you can keep it; we promise. However, if you want Remotii to bill your customers and automatically deliver a monthly direct deposit to your account, then we can do that too. Sign-up for end-user billing, relax and let Remotii Inc. handle the paper work.</p>
      </div>  
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/End-User-Billing.png" alt=""></div>          
    </li>
    
    <li>      
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Reports-And-Stats.png" alt=""></div>
      <div class="con">
        <h4>Reports and Statistics</h4>
        <p>The Remotii RSP portal tracks your sales and monthly income so that you don't have to. </p>
      </div>                  
    </li>
    
    <li>            
      <div class="con">
        <h4>Secure</h4>
        <p>Remotii keeps your data safe. Remotii Inc does not store any credit card or bank account information in our database. Transfers between devices and the Remotii system are encrypted and are not personally identifiable by third parties.</p>
      </div>  
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Secure.png" alt=""></div>      
    </li>
    
    <li>      
      <div class="img"><img src="<?php echo BASE_URL?>/assets/f/images/Getting-Started.png" alt=""></div>              
      <div class="con">
        <h4>Getting Started</h4>
        <p>Sign-up now to begin enjoying the benefit Remotii can bring to your business today.</p>
      </div>        
    </li>

    <li>            
      <div class="" align=right>
        <p>Still Have Questions?<h5><a href="<?php echo BASE_URL . '/contact' ?>">Contact Us</a> </h5></p>
      </div>        
    </li>
       
  </ul>	
</div>

<br>  
      
<div class="content">
    <div class="wrapper page-con">
        <div>
            <a class="btn2 rsp_register_button" href="<?php echo BASE_URL . '/register-rsp' ?>">Register as RSP</a>
        </div>
    </div>
</div>

<!--/content-->





