<?php
$imgPath = BASE_URL . '/assets/f';

$shared_userId = $shared_user_id;
?>
<style>
    #ioalgntop { vertical-align: top; }
</style>
<script>
    ajaxCount = 0;
    remotiiLastInputStatus = '<?php echo $remotiiLastInputStatus; ?>';
    if (typeof String.prototype.trim !== 'function') {
        String.prototype.trim = function () {
            return this.replace(/^\s+|\s+$/g, '');
        }
    }

    var refreshRate_in_msec = 1000; // msec
    var $remotiiList = null;
    var $inboundList = null;
    var $ic_op_status_arr = null;
    var $ic_op_color_arr = null;
    var $ic_out_color_arr = null;
    var $iblisting = null;
    var $iocontrol = null;
    var last_message_id = '0';

    var cacheDOMElems = function () {
        $remotiiList = $('#remotiiList'); // cache remotiiList object
        $inboundList = $('#inbound_list');
        $ic_op_status_arr = [];
        $ic_op_color_arr = [];
        $ic_out_color_arr = [];
        for (var i = 1; i <= 3; i += 1) {
            $ic_op_status_arr[i] = $(".ic_op_status" + i);
            $ic_op_color_arr[i] = $(".ic_op_color" + i)
        }

        for (var i = 1; i <= 4; i += 1) {
            $ic_out_color_arr[i] = $(".ic_out_color" + i);
        }

        $iocontrol = $(".iocontrol");
        $iblisting = $(".iblisting");

    };

    $(document).ready(function () {
        cacheDOMElems();
        loadInboundData();
//        periodicallRefreshShareRemotii();
        $(".ajax").colorbox({width: "50%", height: "420px"});
        $(".iframe").colorbox({iframe: true, width: "55%", height: "420px"});
        $(".iframe2").colorbox({iframe: true, width: "50%", height: "470px"});
        $(".iframe3").colorbox({iframe: true, width: "820px", height: "520px"});
        $(window).scroll(function () {
            if ($(window).scrollTop() == $(document).height() - $(window).height()) {
                loadMoreIBData();
            }
        });

        var previous;
        $remotiiList.focus(function () {
            // Store the current value on focus and on change

            isDisabled = $(this).find('option:selected').hasClass('disabled');
            previous = this.value;
        }).change(function () {
            var remotiiId = $remotiiList.val();

            if ($(this).find('option:selected').hasClass('disabled')) {
                if (isDisabled == false) {
                    //alert(previous);
                    $('#remotiiList').val(previous);
                }
                $('.spinfo').trigger('click');
                return false;
            }

            if (remotiiId == '') {
                window.location.href = '<?php echo BASE_URL; ?>' + '/client/my-remotii';
            }
            if (remotiiId != '') {
                window.location.href = '<?php echo BASE_URL; ?>' + '/client/my-remotii/' + remotiiId;
            }

        });
        $('.ping-auth').click(function () {
            pingAuthentication();
        });

        $('.spinfo').click(function (e) {
            //if($(this).hasClass('iframe2')) return;
            //e.preventDefault();
            var remotiiId = $remotiiList.val();
            var url = '<?php echo BASE_URL; ?>/client/service-provider-info?remotii_id=' + remotiiId;
            $('.spinfo').attr('href', url);//.addClass('iframe2 cboxElement');
            //$('.spinfo').trigger('click');
        });



    });


    function setDefaultRemotii()
    {
        var remotiiId = $remotiiList.val();
        var userId = '<?php echo $userId; ?>';

        jQuery.ajax({
            url: '<?php echo BASE_URL ?>/client/set-default-remotii',
            type: 'post',
            async: true,
            data: {userId: userId, remotiiId: remotiiId},
            success: function (response) {
//                console.log(response);
                response_arr = JSON.parse(response)
                if (response_arr.status == 'OK')
                {
                    var val = $("#remotiiList option:selected").text();
                    if (val.indexOf("default") < 0) {
                        $('#remotiiList option:selected').text(val + '(default)');
                    }
                    window.location.reload();
                }
            }/* ,
             complete:function(response){
             console.log( data );
             } */
        });
    }

//  Function defined to change the out put initial state
    function changeStatusOut(pin_number, status, obj, pulse_width) {
        pingAuthentication();
        if ($(obj).hasClass('disabled')) {
            return;
        }

        if (pin_number == 1) {
            dout_sc = 1;
        } else if (pin_number == 2) {
            dout_sc = 2;
        } else if (pin_number == 3) {
            dout_sc = 4;
        }

        var remotii_id = $("#remotii_id").val();
        var remotii_mac_address = $("#remotii_mac_address").val();
        var targateUrl = '<?php echo BASE_URL ?>/client/change-config-status?pin_number=' + pin_number + '&dout_sc=' + dout_sc + '&remotii_id=' + remotii_id + '&remotii_mac_address=' + remotii_mac_address + '&status=' + status + '&pulse_width=' + pulse_width;

        jQuery.ajax({
            url: targateUrl,
            type: 'get',
            async: true,
            success: function (response) {
                if (response == 0) {
                    window.location.reload();
                }
                // alert(response);
            }
            /*, complete:function(response) {
             console.log(response);
             } */
        });
    }

    function loadIOControl()
    {
        var last_message_elem = $inboundList.find("tr:first");
        last_message_id = last_message_elem.attr("id");

        var outputElem;
        var tooltip = '';
        //alert(last_message_id);
        if (last_message_id != "" && (typeof last_message_id != 'undefined')) {
            for (var i = 1; i <= 3; i++) {
                outputElem = last_message_elem.find(".output" + i);
                out_status = outputElem.find(".status").text();
                state = last_message_elem.find(".output" + i).attr('state');
                //alert("output" + i + "-" + state);
                if ((typeof state == 'undefined')) //break;
                {

                } else
                {
                    if (state.trim() == '1')
                    {
                        state = 'Energized';
                    } else {
                        state = 'Not Energized';
                    }

                    tooltip = 'Pin: ' + i + '\n' + 'State: ' + out_status + ' ( ' + state + ' )';

                    $ic_op_status_arr[i].text(out_status);
                    $ic_op_color_arr[i].css("background", outputElem.find(".status_color").text()).attr("title", tooltip);
                }
            }

            for (var i = 1; i <= 4; i++) {

                state = last_message_elem.find(".input" + i).attr('state');
                in_status = last_message_elem.find(".input" + i + " .status").text();
                //alert("input" + i + "-" +state);
                if ((typeof state == 'undefined')) //break;
                {

                } else
                {
                    if (state.trim() == '1')
                    {
                        state = 'Energized';
                    } else {
                        state = 'Not Energized';
                    }

                    tooltip = 'Pin: ' + i + '\n' + 'State: ' + in_status + ' ( ' + state + ' )';

                    $ic_out_color_arr[i].css("background", last_message_elem.find(".input" + i + " .status_color").text()).attr("title", tooltip);
                }
            }
        }
        $iocontrol.show();
    }

    var updateView = function (response) {

        $inboundList.prepend(response);//add entry to table
        remotii_id = $('.permission:first').attr('remotii_id');
        remotiiLastInputStatus = $('.recent-status:first').val();
        remotiiLastOutputStatus = $('.recent-output-status:first').val();

        $('.din').val(remotiiLastInputStatus);
        $('.dout').val(remotiiLastOutputStatus);
        var playChime = $('.alarm:first').val();
        var heartbeattime = $('.heartbeat:first').val();
        var lastrecievedtime = $('#inbound_list').find('tr:first').find('td:first').attr('time');
        date1 = new Date(heartbeattime);
        date2 = new Date(lastrecievedtime);
        if (date1 > date2) {
            $('.ajx-time').html(" <h4>Last Updated:</h4><label id='latest_time'>" + '   ' + heartbeattime + "<label>");
        } else {
            if (typeof lastrecievedtime !== 'undefined') {
                $('.ajx-time').html(" <h4>Last Updated:</h4><label id='latest_time'>" + '   ' + lastrecievedtime + "<label>");
            }
        }

        $iblisting.show();
//        alert(playChime);
        if (playChime == 1) {
            var audioElement = document.createElement('audio');
            audioElement.setAttribute('src', '<?php echo BASE_URL; ?>' + '/assets/f/audio/beep.mp3');
            audioElement.setAttribute('autoplay', 'autoplay');
            audioElement.setAttribute('type', 'audio/mpeg');
            audioElement.load();
            audioElement.play();
        }

        if (remotii_id == '') {
            // window.location.reload();
            window.location.href = '<?php echo BASE_URL; ?>' + '/client/my-remotii';
        }
        permission = $('.permission:first').attr('permission');
        $('.permission').remove();
        $('.heartbeat').remove();
        $('.recent-status').remove();
        $('.alarm').remove();
        switch (permission) {
            case "1":
                $('input[name=toggleBtn],input[name=button]').show();
                $('.iblisting').removeClass('disabled');
                break;
            case "2":
                $('input[name=toggleBtn],input[name=button]').show();
                if (!$('.iblisting').hasClass('disabled')) {
                    $('.iblisting').addClass('disabled');
                }
                break;
            default:
                $('input[name=toggleBtn],input[name=button]').hide();
                $('.iblisting').removeClass('disabled');
        }

        loadIOControl();
    };
    
    function loadInboundData()
    {
        var timezone_offset_minutes = new Date().getTimezoneOffset();
        timezone_offset_minutes = timezone_offset_minutes == 0 ? 0 : -timezone_offset_minutes;
        var remotii_id = $remotiiList.val();
        var oldDin = $('.din').val();
        var oldDout = $('.dout').val();
        if (remotii_id == "")
            return;
        if (last_message_id == "")
            last_message_id = 0;
        targateUrl = '<?php echo BASE_URL ?>/client/ajx-get-inbound-data?limit=50&remotii_id=' + remotii_id + '&last_message_id=' + last_message_id + '&oldDin=' + oldDin + '&oldDout='+oldDout+'&ajax_count=' + ajaxCount++;

        jQuery.ajax({
            url: targateUrl,
            type: 'get',
            async: true,
            data: {id:Intl.DateTimeFormat().resolvedOptions().timeZone},
            success: function (response) {
               // console.log(response);
                chkSession(response);
                updateView(response);
            },
            complete: function (response) {
                setTimeout(loadInboundData, refreshRate_in_msec);

            }
        });
    }

//    var updateView = function(response) {
//        $inboundList.prepend(response); // add entry to table
//        $iblisting.show();
//        loadIOControl();
//    };

    function chkSession(response)
    {
        try {
            res_obj = $.parseJSON(response);
//            console.log(res_obj);
            if (res_obj.session_expired == '1')
            {
                window.top.location.href = "<?php print BASE_URL . '/user/login?se=1&mc=1&redirect=' . $this->serverUrl(true); ?>";
            }
        } catch (e) {
            // not json
        }
    }

    function loadMoreIBData()
    {
        var timezone_offset_minutes = new Date().getTimezoneOffset();
        timezone_offset_minutes = timezone_offset_minutes == 0 ? 0 : -timezone_offset_minutes;
        var remotii_id = $remotiiList.val();
        if (remotii_id == "")
            return;
        var message_id = $inboundList.children("tr:last").attr('id');
        if (message_id == "")
            return;

        targateUrl = '<?php echo BASE_URL ?>/client/ajx-get-inbound-data?limit=50&ltmsgid=1&remotii_id=' + remotii_id + '&last_message_id=' + message_id;

        target = document.getElementById('load_more_ib');
        opts.top = 20;
        var spinner = new Spinner(opts);
        spinner.spin(target);

        jQuery.ajax({
            url: targateUrl,
            type: 'get',
            async: true,
            data: {id:Intl.DateTimeFormat().resolvedOptions().timeZone},
            success: function (response) {
                ;
                $inboundList.append(response);
                permission = $('.permission:first').attr('permission');
                $('.permission').remove();
            },
            complete: function (response) {
                spinner.stop(target);
            }
        });

    }


</script>

<style>
    .status_color{display:none;}
    .din_value{display: none;}
</style>
<!-- Tag line  -->
<div class="tag-line">
    <div class="wrapper">
        <h2>User Remotii</h2>
    </div>
</div>
<!-- Tag line ends -->
<div class="content">
    <div class="wrapper">
        <div class="heading"> 
<?php if ($remotiiId || !empty($userRemotii)): ?>

                <h2>Viewing</h2>
                <label class="sel">
                    <select name="remotiiList" id="remotiiList">
    <?php
    $i = 0;
    foreach ($userRemotii as $uData) {
        if ($uData->remotii_id == $remotiiId) {
            //$defaultRemotiiId = $uData->remotii_id;
            $selectd = 'selected';
        } else {
            $selectd = '';
        }
        ?>
                            <?php if ($i == 0) { ?>

                                <option value="">All remotii</option>
                            <?php } ?>
                            <option value="<?php print $uData->remotii_id; ?>"  value1="<?php print $uData->mac_address; ?>" <?php
                    if ($uData->remotii_status != ACTIVE) {
                        echo 'class="disabled"';
                    }
                            ?>
                            <?php print $selectd; ?>>
                            <?php
                            if ($uData->remotii_status == ACTIVE) {
                                if ($uData->user_id == $userId) {

                                    if ($uData->ur_default == 1) {
                                        print $uData->remotii_name . " " . '(default)';
                                    } else {
                                        print $uData->remotii_name;
                                    }
                                } else if ($uData->user_id != $userId) {
                                    if ($uData->sr_is_default == 1) {
                                        print $uData->remotii_name . " " . '(default)';
                                    } else {
                                        print $uData->remotii_name;
                                    }
                                }
                                ?>
                                            <?php
                                        } else {
                                            print $uData->remotii_name . ' (Suspended)';
                                        }
                                        ?>

                            </option> 

        <?php
        $i++;
    }
    ?>
                    </select>
                </label>
    <!--                 <div class="box1 iblisting <?php echo ($userRemotiiConfig['baseRec'][0]['access_level'] != 2) ? "" : "disabled"; ?>" style="display: none;">
                <table cellpadding="0" cellspacing="0" border="0" class="table1"
                       >
                    <thead>

                        <tr>
                            <th>Event Time</th>
                            
                        </tr>

                    </thead>
    <?php // if ($userRemotiiConfig['baseRec'][0]['access_level'] != 2) {      ?>
                    <tbody id="inbound_list">

                    </tbody>
    <?php // }      ?>
                </table>
            </div>-->
                <div class="setting-option">
                    <a href="javascript:void(0);" class="btn-red setting-btn"> 
                        <span> 
                            Action
                        </span>
                    </a>

                    <ul>
                        <li><a href="<?php echo BASE_URL ?>/client/service-provider-info?remotii_id=<?php echo $remotiiId; ?>"
                               class="spinfo iframe4 ping-auth">Service Provider Info</a></li>
                        <li><a class="iframe3 ping-auth" href="<?php print BASE_URL . '/client/remotii-setup' ?>">Add New Remotii</a></li>	
    <?php
    //foreach($userRemotii as $uData) {
    ?>
                        <li class="rm modifySettings"
                        <?php if ($userRemotiiConfig['baseRec'][0]['user_id'] == $this->userId || $userRemotiiConfig['baseRec'][0]['access_level'] == 1) { ?>
                                id="rm<?php print $remotiiId; ?>"
                            <?php
                            if (!$remotiiId) {
                                print 'style="display: none;"';
                            }
                            ?>><a
                                    class="iframe3 ping-auth"
                                    href="<?php print BASE_URL . '/client/remotii-setup/' . $remotiiId; ?>">Modify
                                    Settings</a><?php } ?></li>
    <?php
    //}
    ?>
                        <li class="rm modifySettings"
                        <?php if ($userRemotiiConfig['baseRec'][0]['user_id'] == $this->userId || $userRemotiiConfig['baseRec'][0]['access_level'] == 1) { ?>
                                id="rm<?php print $remotiiId; ?>"
                            <?php
                            if (!$remotiiId) {
                                print 'style="display: none;"';
                            }
                            ?>><a
                                    class="iframe3 ping-auth"
                                    href="<?php print BASE_URL . '/client/event-scheduler/' . $remotiiId; ?>">Schedule Events
                                </a><<?php } ?>/li>
                        <li class="rm modifySettings"
                        <?php if ($userRemotiiConfig['baseRec'][0]['user_id'] == $this->userId || $userRemotiiConfig['baseRec'][0]['access_level'] == 1) { ?>
                                id="rm<?php print $remotiiId; ?>"
                            <?php
                            if (!$remotiiId) {
                                print 'style="display: none;"';
                            }
                            ?>><a
                                    class="iframe3 ping-auth"
                                    href="<?php print BASE_URL . '/client/chained-event-scheduler/' . $remotiiId; ?>">Chained Events
                                </a><<?php } ?>/li>
                        <li class="rm modifySettings"
    <?php if ($userRemotiiConfig['baseRec'][0]['user_id'] == $this->userId) { ?>
                                id="rm<?php print $remotiiId; ?>"
                            <?php
                            if (!$remotiiId) {
                                print 'style="display: none;"';
                            }
                            ?>><a
                                    class="iframe3 ping-auth"
                                    href="<?php print BASE_URL . '/client/remotii-sharing/' . $remotiiId; ?>">Share Remotii
                                </a><?php } ?></li>

                        <li><a href="#" onclick="setDefaultRemotii();">Set as Default</a></li>
                    </ul>
                </div>
                &nbsp;&nbsp;
    <?php if ($userRemotiiConfig['baseRec'][0]['user_id'] != $userId) { ?>
                    <div class="share-sec">
                        <span  class="simg"> <img src='<?php echo $imgPath . "/images/share-me.png"; ?>' ></span>
                        <ul>
                            <li>
        <?php print "Shared with me by " . "<font color='red'> $share_person_name </font>"; ?> </li>
                        </ul>
                    </div>
                            <?php } ?>
    <?php if ($userRemotiiConfig['baseRec'][0]['user_id'] == $userId && count($userRemotiiConfig['baseRec'][0]['shared_user']) > 0) { ?>
                    <div class="share-sec2">
                        <span class="simg"> <img src='<?php echo $imgPath . "/images/share-other.png"; ?>' ></span>
                        <ul  style="" >
        <?php
        if (count($userRemotiiConfig['baseRec'][0]['shared_user']) > 0) {
            ?><li><?php print "Shared With:"; ?></li><?php
                                foreach ($userRemotiiConfig['baseRec'][0]['shared_user'] as $shared_with_other) {
                                    ?><li><?php print $shared_with_other['username']; ?></li>
                                    <?php
                                }
                            }
                            ?>
                        </ul>
                    </div>

    <?php }
    ?>

            <?php else: ?>
                <div style="text-align: center;">
                    <div class="" style="font-size: 29px;
                         margin-bottom:40px;
                         font-weight: 500px;">
                        You currently have no configured Remotii's. Please click <br/>below to add a Remotii to your account.
                    </div>
                    <div>
                        <a class="btn-blue iframe3" href="<?php print BASE_URL . '/client/remotii-setup' ?>">Add New Remotii</a>
                    </div>
                </div>
<?php endif; ?>
        </div>
        <div class="ajx-time">

            <h4>Last Updated:</h4>   <span>  <label id="latest_time"></label></span>

        </div>
        <input type="hidden" class="max_time" value="<?php echo $time ?>">
        <input type="hidden" class="dout" value="<?php echo $userRemotiiConfig['baseRec'][0]['remotii_last_output_status']; ?>">

<?php if ($remotiiId || !empty($userRemotiiConfig['baseRec'][0]['remotii_id'])): ?>
            <div>
                <input type="hidden" id="remotii_mac_address" value="<?php echo $userRemotiiConfig['baseRec'][0]['mac_address'] ?>" />
                <input type="hidden" id="remotii_id" value="<?php echo $userRemotiiConfig['baseRec'][0]['remotii_id'] ?>" />
            </div>
            <div class="iocontrol" style="display:none;">
                <h4><span>Output Status</span><span style='float:right'>Output Control</span></h4>
               
                
                <div class="box1 viewing">
    <?php
    //_pr($userRemotiiConfig);
    ?>
                    <ul class="list2 alter">
                    <?php
                    // _pr($userRemotiiConf);
                    $i = 0;
                    foreach ($userRemotiiConfig['outConfig'] as $outConfig) {
                        //$i++;
                        $i = $outConfig['pin_number'];
                        $tooltip = 'Pin: ' . $outConfig['pin_number'] . '&#10;' . 'State: ' . $outConfig['active_label_text'] . ' ( Energized )';
                        ?>
                            <li>
                                <div class="fl">
                                    <span class="name ic_op_name<?php echo $i; ?>">
        <?php print $outConfig['name']; ?>
                                    </span>
                                    <span title="<?php echo $tooltip ?>" class="color-output ic_op_color<?php echo $i; ?>" id="statusClr<?php print $outConfig['config_id']; ?>" style="background: 
                                        <?php
                                        if ($outConfig['output_initial_state'] == 1) {
                                            print $outConfig['active_label_color'];
                                        } else {
                                            print $outConfig['inactive_label_color'];
                                        }
                                        ?>;">
                                    </span>

                                    <label id="statusTxt<?php print $outConfig['config_id']; ?>" class="ic_op_status<?php echo $i; ?>">
        <?php
        if ($outConfig['output_initial_state'] == 1) {
            print $outConfig['active_label_text'];
        } else {
            print $outConfig['inactive_label_text'];
        }
        ?>
                                    </label>
                                </div>
                                <div class="fr">
                                    <input type="hidden" value="<?php echo $outConfig['pulse_width']; ?>" name=pulse_<?php echo $i ?>>
        <?php
        if ($userRemotiiConfig['baseRec'][0]['user_id'] == $this->userId || $userRemotiiConfig['baseRec'][0]['access_level'] == 1 || $userRemotiiConfig['baseRec'][0]['access_level'] == 2) {
            if ($outConfig['is_output_momentary'] == '1') {
                $class = 'disabled btn6';
            } else {
                $class = 'btn5';
            }
            ?>

                                        <?php if ($outConfig['is_output_momentary'] != '1'): ?>
                                            <input type="button" name="button" class="<?php echo $class; ?> ic_op_active<?php echo $i; ?>"
                                                   id="actBtn<?php print $outConfig['config_id']; ?>"
                                                   data-value="<?php print $outConfig['output_initial_state']; ?>"
                                                   value="<?php print $outConfig['active_label_text']; ?>"
                                                   onclick="changeStatusOut(<?php echo $i ?>, 'set', this, '<?php echo $outConfig['pulse_width']; ?>');"/>

                                            <input type="button" name="button" class="<?php echo $class; ?> ic_op_inactive<?php echo $i; ?>"
                                                   id="inactBtn<?php print $outConfig['config_id']; ?>" 
                                                   data-value="<?php print $outConfig['output_initial_state']; ?>"
                                                   value="<?php print $outConfig['inactive_label_text']; ?>"
                                                   onclick="changeStatusOut(<?php echo $i ?>, 'clr', this, '<?php echo $outConfig['pulse_width']; ?>');" />
            <?php else: ?>
                <?php if ($outConfig['is_output_momentary'] == 1) { ?>
                                                <input type="button" name="toggleBtn"
                                                       value=" <?php print $outConfig['name']; ?> " class="btn5" onclick="changeStatusOut(<?php echo $i ?>, 'tgl', this, '<?php echo $outConfig['pulse_width']; ?>');"/>
                                                   <?php } else { ?>
                                                <input type="button" name="toggleBtn"
                                                       value="Toggle" class="btn6" disabled />
                                                   <?php } ?>
            <?php endif; ?>
                                           <?php } ?>
                                </div>
                            </li>
                                           <?php
                                       }
                                       ?>
                    </ul>
                </div>

                <h4>Input Status</h4>
                <div class="box1">

                    <input type="hidden" class="din" value="<?php echo $userRemotiiConfig['baseRec'][0]['remotii_last_input_status']; ?>">

                    <div class="input-color-wrap">
    <?php
    $i = 0;

    $rmLastStatus = $userRemotiiConfig['baseRec'][0]['remotii_last_input_status'];
    foreach ($userRemotiiConfig['inConfig'] as $inConfig) {
        $i = $inConfig['pin_number'];

        if ($i == 1) {
            if ($rmLastStatus & 1) {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['active_label_text'] . ' ( Energized )';

                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['active_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            } else {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['inactive_label_text'] . ' ( Not Energized )';
                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['inactive_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            }
        }

        if ($i == 2) {
            if ($rmLastStatus & 2) {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['active_label_text'] . ' ( Energized )';

                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['active_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            } else {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['inactive_label_text'] . ' ( Not Energized )';
                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['inactive_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            }
        }

        if ($i == 3) {
            if ($rmLastStatus & 4) {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['active_label_text'] . ' ( Energized )';

                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['active_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            } else {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['inactive_label_text'] . ' ( Not Energized )';
                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['inactive_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            }
        }

        if ($i == 4) {
            if ($rmLastStatus & 8) {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['active_label_text'] . ' ( Energized )';
                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['active_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            } else {
                $tooltip = 'Pin: ' . $inConfig['pin_number'] . '&#10;' . 'State: ' . $inConfig['inactive_label_text'] . ' ( Not Energized )';
                print $custData = '<div class="input-color">
                                    <span title="' . $tooltip . '" class="ic_out_color' . $i . '" style="background: ' . $inConfig['inactive_label_color'] . ';"></span>
                                    ' . $inConfig['name'] . '
                                </div>';
            }
        }
    }
    ?>
                    </div>  
                </div>
            </div>
    <?php // if ($userRemotiiConfig['baseRec'][0]['access_level'] != 2) {      ?>
            <div class="box1 iblisting <?php echo ($userRemotiiConfig['baseRec'][0]['access_level'] != 2) ? "" : "disabled"; ?>" style="display: none;">
                <table cellpadding="0" cellspacing="0" border="0" class="table1"
                       width="100%">
                    <thead>

                        <tr>
                            <th>Event Time</th>
                            <th>Input Status</th>
                            <th>Output Status</th>
                        </tr>

                    </thead>
    <?php // if ($userRemotiiConfig['baseRec'][0]['access_level'] != 2) {      ?>
                    <tbody id="inbound_list">

                    </tbody>
    <?php // }      ?>
                </table>
            </div>

    <?php // }    ?>
            <div id="load_more_ib" style="margin-bottom:200px;"></div>
        <?php endif; ?>
    </div>
</div>

<!--/content-->
<script type="text/javascript" src="<?php echo BASE_URL . '/assets/c/js/spin.js' ?>"></script>
<script>
                                       var opts = {
                                           lines: 10, // The number of lines to draw
                                           length: 10, // The length of each line
                                           width: 4, // The line thickness
                                           radius: 10, // The radius of the inner circle
                                           corners: 1, // Corner roundness (0..1)
                                           rotate: 0, // The rotation offset
                                           direction: 1, // 1: clockwise, -1: counterclockwise
                                           color: '#000', // #rgb or #rrggbb or array of colors
                                           speed: 1, // Rounds per second
                                           trail: 60, // Afterglow percentage
                                           shadow: false, // Whether to render a shadow
                                           hwaccel: false, // Whether to use hardware acceleration
                                           className: 'spinner', // The CSS class to assign to the spinner
                                           zIndex: 2e9, // The z-index (defaults to 2000000000)
                                           top: 'auto', // Top position relative to parent in px
                                           left: 'auto' // Left position relative to parent in px
                                       };
</script>