<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">   
    <h2>Remotii News</h2>
  </div>
</div>
<!-- Tag line ends --> 
<div class="content">
<div class="wrapper page-con">
<h3 class="heading3">Latest News</h3>
            <li>
			<h4><a href="#">Remotii Scheduler</a></h4> Remotii's advanced scheduling feature is coming soon. With the Remotii Scheduler, you can configure a series of actions to 			
			be setup in advance. Good bye timers, Hello Remotii.
			</li>
			<li>
			<h4><a href="#">Remotii Events</a></h4> Remotii Events are coming.  Remotii Events will enable Remotii devices to talk with one another. You could setup a motion sensor in one place and activate the lights in several other places.
			</li>
			<li>
			<h4><a href="#">Remotii's at a glance</a></h4> if you have more than one
        	</li>
</div>
</div>
<!--/content-->