<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">   
    <h2>Remotii Uses</h2>
  </div>
</div>
<!-- Tag line ends --> 
<div class="content">
<div class="wrapper page-con">
	<h3 class="heading3">Below are just a few of the great things you can do with your Remotii.</h3>
	<ul class="list">
		<li>Arm, disarm or simply monitor the state of your security system.</li>
		<li>Monitor or control location temperature.</li>
		<li>Open or close your garage door.</li>
		<li>Turn on or off interior or exterior lights.</li>
        <li>Snap a picture from an IP camera when something else happens.</li>
        <li>Detect water in the basement or if your boat is sinking.</li>
        <li>Humidity control.</li>
        <li>Feed the dog, cat or fish.</li>
        <li>Event notification button.</li>
        <li>Mail box monitor.</li>
	</ul>  
</div>
</div>
<!--/content-->