<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Remotii Enduser</title>
        <?php $baseUrl = BASE_URL . "/assets/f"; ?>
        <link href="<?php echo $baseUrl; ?>/css/reset.css" type="text/css" rel="stylesheet">
        <link href="<?php echo $baseUrl; ?>/css/main.css" type="text/css" rel="stylesheet" charset="utf-8">
        <?php echo $this->headLink()->appendStylesheet($baseUrl . '/css/main-phase2.css'); ?>
        <link href="<?php echo $baseUrl; ?>/css/main-phase2.css" type="text/css" rel="stylesheet" charset="utf-8">
        <link href="<?php echo $baseUrl; ?>/css/buttons.css" type="text/css" rel="stylesheet" charset="utf-8">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
        <link href="<?php echo $baseUrl; ?>/css/screen.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?php echo $baseUrl; ?>/css/colorbox.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="<?php echo $baseUrl; ?>/css/jquery-ui.css" rel="stylesheet" type="text/css" media="screen" />
        <script src="<?php echo $baseUrl; ?>/js/jquery-1.7.1.min.js" type="text/javascript"></script>
        <script src="<?php echo $baseUrl; ?>/js/jquery-ui.js" type="text/javascript"></script>
        <script  type="text/javascript" src="<?php echo $baseUrl; ?>/js/custom.js"></script>
        <script type="text/javascript" src="<?php echo $baseUrl; ?>/js/easySlider1.7.js"></script>
        <!--<script type="text/javascript" src="<?php echo $baseUrl; ?>/assets/b/js/jquery.colorbox.js"></script>-->
        <style>

            a.right{background: url(../../assets/f/images/right-small.png) no-repeat scroll 100% 100% rgba(0, 0, 0, 0);
                    display: inline-block;
                    height: 20px;
                    margin-left: -28px;
                    margin-top: 14px;
                    position: absolute;
                    width: 18px;}
            a.wrong{
                background: url("../../assets/f/images/cross.png") no-repeat scroll 100% 100% rgba(0, 0, 0, 0);
                display: inline-block;
                height: 20px;
                margin-left: -28px;
                margin-top: 14px;
                position: absolute;
                width: 18px;
                /*background: url(../images/cross.png) 50% 50% no-repeat; height: 13px; width: 13px;*/
            }
            .message{
                text-align: center;
                padding-top: 90px;
                font-size: 20px;
            }
            
            .shareWrap select, .sharebox select{padding:5px 3px;  vertical-align: middle;}
            .sharebox input[type="text"]{ height: 29px; line-height:29px; vertical-align: middle;}
            .sharebox .btn3{ height: 32px; line-height: 30px; vertical-align: middle;}
        </style>
    </head>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".share").blur(function(e) {
                if($(this).val().trim() != '')
                    {
                
                email = $(this).val();
                obj = $(this).parent('div').find('.btn3');
                loader = $(this).parent('div').find('.img_loader');
                obj.addClass('wrong1');
                error = $(this).parent('div').find('.err');
                error1 = $(this).parent('div').find('.err1');
                loader.removeClass('hide');
                $.post("<?php echo BASE_URL . "/client/iajax"; ?>",
                        {
                            action: "checkemail",
                            params: {
                                email: email,
                                remotii_id: "<?php echo $this->id; ?>",
                            }
                        },
                function(data) {
                    loader.addClass('hide');
                    if (data.status == "success") {
                        obj.removeClass('wrong1');
                        obj.addClass('right1');
                        $('.err').hide();

                    }
                    else {
                        obj.removeClass('right1');
                        obj.addClass('wrong1');
                        $('.err').html(data.errmess);
                        $('.err').show();
                    }
                },
                        "json");
                }
            });

            $(".select2").live("change", function(e) {
                access_level = $(this).val();
                remotii_id = $(this).attr('remotii_id');
                email = $(this).attr('email');
                $.post("<?php echo BASE_URL . "/client/iajax"; ?>",
                        {
                            action: "editAccess",
                            params: {
                                access_level: access_level,
                                remotii_id: remotii_id,
                                email: email,
                            }
                        },
                function(data) {
                    console.log(data);
                    if (data.status == "success") {
                    }
                    else {
                        alert(data.result);
                    }
                },
                        "json");
            });


            $(".btn3").click(function(e) {
//                if ($(this).hasClass("wrong1")) {
//                    return false;
//                }
             
              obj=$(this).parent('div').parent('div').find('.share_table');
                AccessId = $(this).parent().find('.select1').val();
                email = $(this).parent().find('.share').val();
                remotii_id = $(this).attr('remotii_id');
                message_obj=$('.message');
                $.post("<?php echo BASE_URL . "/client/iajax"; ?>",
                        {
                            action: "InsertSharePerson",
                            params: {
                                AccessId: AccessId,
                                email: email,
                                remotii_id: remotii_id,
                            }
                        },
                function(data) {
                    console.log(data);
                    if (data.status == "success") {
                        // window.location.reload();
                        //alert(email);
                        if(AccessId==1){
                        obj.append('<tr class="sp"><td>'+email+'</td>\n\
                                    <td>'+data.username+'</td>\n\
                                    <td><select class="select2" email="'+email+'" remotii_id="'+remotii_id+'")><option value="1" selected="selected">Full Access</option>\n\
                                                <option value="2">Control with No Logs</option>\n\
                                                <option value="3" >View Only</option></select></td>\n\
                                     <td><a href="#" class="delete_share" remotii_id="'+remotii_id+'" email="'+email+'">&nbsp</a></td></tr>');
                                         }
                                          if(AccessId==2){
                        obj.append('<tr class="sp"><td>'+email+'</td>\n\
                                    <td>'+data.username+'</td>\n\
                                    <td><select class="select2" email="'+email+'" remotii_id="'+remotii_id+'")><option value="1">Full Access</option>\n\
                                                <option value="2" selected="selected">Control with No Logs</option>\n\
                                                <option value="3" >View Only</option></select></td>\n\
                                     <td><a href="#" class="delete_share" remotii_id="'+remotii_id+'" email="'+email+'">&nbsp</a></td></tr>');
                                         }
                                          if(AccessId==3){
                        obj.append('<tr class="sp"><td>'+email+'</td>\n\
                                    <td>'+data.username+'</td>\n\
                                    <td><select class="select2" email="'+email+'" remotii_id="'+remotii_id+'")><option value="1" selected="selected">Full Access</option>\n\
                                                <option value="2">Control with No Logs</option>\n\
                                                <option value="3" selected="selected">View Only</option></select></td>\n\
                                     <td><a href="#" class="delete_share" remotii_id="'+remotii_id+'" email="'+email+'">&nbsp</a></td></tr>');
                                         }
                                         
                                         message_obj.text('');
                                         message_obj.removeClass('message');
                                                                           
                    }
                    else {
                        obj.removeClass('right1');
                        obj.addClass('wrong1');
                        $('.err').html(data.errmess);
                        $('.err').show();
                    }
                },
                        "json");
                e.preventDefault();
                $(this).parent().find('.share').val('');
            });

            $(".delete_share").live("click", function(e) {
                if(confirm("Are you sure to unshare the remotii with this user?"))
                    {
                email = $(this).attr('email');
              //  alert(email);
                obj = $(this).parent().parent();
                remotii_id = $(this).attr('remotii_id');
                $.post("<?php echo BASE_URL . "/client/iajax"; ?>",
                        {
                            action: "deleteShare",
                            params: {
                                email: email,
                                remotii_id: remotii_id,
                            }
                        },
                function(data) {
                    console.log(data);
                    // alert(data);
                    if (data.status == "success") {
                        //window.location.reload();
                        obj.remove();
                    }
                    else {
                        alert(data.result);
                    }
                },
                        "json");
                
                }
                e.preventDefault();
            });
        });
    </script>

    <body>
        <div class="remotii-setup sharing">
            <h2>Sharing Remotii&nbsp-&nbsp;<span><?php print $remotiiname; ?></span></h2>
            <h4>Sharing with: </h4>
            <div class="form rinput">
                <div class="shareWrap">
                    <table val="1"class="share_table" width="100%" cellspacing="0" cellpadding="0" >
                        <?php if (!empty($message)) { ?>
                            <div class="message"> <?php echo $message; ?></div>
                        <?php } ?>
                        <?php foreach ($SharePersons as $persons) { ?>
                            <tr class="sp">
                                <td><?php echo $persons->email; ?></td>
                                <td><?php echo $persons->username; ?></td>
                                <td><select class="select2" email="<?php echo $persons->email; ?>" remotii_id="<?php print $id; ?>">
                                        <option value="1" <?php if ($persons->access_level == 1) echo "selected='selected'"; ?>>Full Access</option>
                                        <option value="2" <?php if ($persons->access_level == 2) echo "selected='selected'"; ?>>Control with No Logs</option>
                                        <option value="3" <?php if ($persons->access_level == 3) echo "selected='selected'"; ?>>View Only</option>
                                    </select>
                                </td>
                                <td><a href="#" class="delete_share" remotii_id="<?php print $id; ?>" email="<?php echo $persons->email; ?>">
                                        &nbsp;
                                    </a></td>

                            </tr> <?php } ?>                          
                    </table>
                </div>
                <br>
                <div class="box1 sharebox">
                    <label>Share With</label>
                    <input type="text" class="share" placeholder="email"/>
                    <select class="select1">
                        <option value="1">Full Access</option>
                        <option value="2">Control with No Logs</option>
                        <option value="3">View Only</option>
                    </select>
                    <a href="#" class="btn3 wrong1" remotii_id="<?php print $id; ?>">Add</a>
                    <span class="err" style="display:none">User not found.</span>
                </div>
            </div>
        </div>
    </body>
