<!-- Tag line  -->
<div class="tag-line">
  <div class="wrapper">  
    <h2>User Remotii</h2>   
  </div>
</div>
<!-- Tag line ends --> 
<div class="content">
<div class="wrapper">
	<div class="heading">  	
	<h2>Where to buy</h2>

	 </div> 
   <div class="buy-filter">
<label class="sel"><select><option>Your Country</option><option>Your Country</option></select></label>
<label class="sel"><select><option>Your State</option><option>Your State</option></select></label>
<label class="sel"><select><option>Your City</option><option>Your City</option></select></label>
<label class="sel"><select><option>See Locations</option><option>See Locations</option></select></label>
</div>
<div class="box1">
		<table  cellpadding="0" cellspacing="0" border="0" class="table1" width="100%">
	
			<tbody>
              <tr>
                            
                <td>
                	<p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
				</td>                
                <td>
                	<p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
				</td>  
                 <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>                            
              </tr>
               
              <tr>
                            
                <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>  
                 <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>                            
              </tr>
              <tr>
                            
                <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>  
                 <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>                            
              </tr>
              <tr>
                            
                <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>  
                 <td>
                  <p>CHRIS NISWANDEE<br>
                    SMALLSYS INC<br>
                    795 E DRAGRAM<br>
                    TUCSON AZ 85705<br>
                    USA
                  </p>
        </td>                
                <td>
                  <p>JOHN SMITH<br>
                    100 MAIN ST<br>
                    PO BOX 1022<br>
                    SEATTLE WA 98104<br>
                    USA
                  </p>
        </td>                            
              </tr>
          </tbody>
		</table>
	</div>

</div>
</div>
<!--/content-->