<?php
$baseUrl = BASE_URL . '/assets/b';
echo $this->doctype();

$spInputConfig = $this->SPInputConfig;
$spOutputConfig = $this->SPOutputConfig;
$greenColor = '#00CC00';
$redColor = '#FF0000';
//_pre($spInputConfig);
//_pre($spOutputConfig);
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Remotii')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>-->
        <?php
        $this->headMeta()->appendName("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", "viewport");
        $this->headLink()->appendStylesheet($baseUrl . '/css/styles.css');
        $this->headLink()->appendStylesheet($baseUrl . '/css/popup.css');
        $this->headLink()->appendStylesheet($baseUrl . '/css/screen.css');
        $this->headLink()->appendStylesheet($baseUrl . '/css/evol.colorpicker.css');

        echo $this->headlink();
        ?>
        <script src="<?php echo $baseUrl ?>/js/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $baseUrl ?>/js/easySlider1.7.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $baseUrl ?>/js/evol.colorpicker.js"></script>


        <script type="text/javascript">
            var rsw_error_flag = 0;

            function rsw_validate()
            {
                rsw_error_flag = 0;
                var pageno = $(".pageno span").text();
                var page_numbers = new Array();

                /**
                 * In case of modify remotii
                 */
                page_numbers[3] = '3';
                page_numbers[6] = '6';
                page_numbers[7] = '7';

                page_validate_no = page_numbers.indexOf(pageno);

                if (page_validate_no !== -1) {
                    $(".rsw_v" + page_validate_no + " .rsw_vr").each(function() {
                        if ("" == $(this).val() && !$(this).is(':disabled'))
                        {
                            $(this).css('border', '1px solid red');
                            $(this).click(function() {
                                $(this).css("border", "1px solid #C4C4C4");
                            });
                            rsw_error_flag = 1;
                        }
                    });
                    if (pageno == 7) {
                        $(".pulse-time").each(function()
                        {
                            var value = $(this).val();
                            if (value < 0.1) {
                                $(this).css('border', '1px solid red');
                                rsw_error_flag = 1;
                                return false;
                            }
                            else {
                                $(this).css("border", "1px solid #C4C4C4");

                            }
                        });
                    }
                }

            }

            function check_momentary_output(id) {
                var arr = id.split('_');
                var io = arr[2];
                momentry_check_id = "#" + id;
                if ($(momentry_check_id).is(":checked")) {
                    $("#ro_active_initialState_" + io).attr("disabled", false);
                    $("#ro_inactive_initialState_" + io).attr("disabled", false);
                    $("#ro_inactive_initialState_" + io).prop('checked', true);
                    $("#ro_step2_time_" + io).attr("disabled", false);

                }
                else {
                    $("#ro_active_initialState_" + io).prop('checked', false);
                    $("#ro_inactive_initialState_" + io).prop('checked', false);
                    $("#ro_active_initialState_" + io).attr("disabled", true);
                    $("#ro_inactive_initialState_" + io).attr("disabled", true);
                    $("#ro_step2_time_" + io).attr("disabled", true);
//                    $("#ro_step2_time_" + io).val("1");
                }
                ro_step2_time = $("#ro_step2_time_" + io).val() ? $("#ro_step2_time_" + io).val() : 1;
                $("#ro_step2_time_" + io).val(ro_step2_time);
            }

            $(document).ready(function() {

                $(".drs_cancel").click(function() {
                    $("#cboxClose", parent.document).trigger('click');
                });

                $("#slider ul li").css({width: '670px', height: '350px'});
                $("#slider").easySlider();

                $('.noIndColor').colorpicker({
                    displayIndicator: false,
                    width: "0px"
                });
                $("#nextBtn").click(function() {
                    var pageno = $(".pageno span").text()

                    for (var x = 1; x <= 4; x++) {
                        var ri_enabled_x = $("#ri_enabled_" + x).is(':checked');

                        if (ri_enabled_x)
                        {
                            //$("#ri_enable_ntfn_"+x).attr("checked","checked");

                            $("#ri_input_name_" + x).text($("#ri_name_" + x).val());
                            $("#ri_active_label_" + x).text($("#ri_asl_" + x).val());
                            $("#ri_inactive_label_" + x).text($("#ri_iasl_" + x).val());

                            $("#ri_enable_ntfn_" + x).attr("disabled", false);
                            var ri_enable_ntfn_x = $("#ri_enable_ntfn_" + x).is(':checked');
                            if (ri_enable_ntfn_x) {
                                $("#ri_sound_" + x).attr("disabled", false);
                                $("#ri_ntfn_active_trigger_" + x).attr("disabled", false);
                                $("#ri_ntfn_inactive_trigger_" + x).attr("disabled", false);
                                $("#ri_ntfn_any_trigger_" + x).attr("disabled", false);
                            } else {
                                $("#ri_sound_" + x).attr("disabled", "disabled");
                                $("#ri_ntfn_active_trigger_" + x).attr("disabled", "disabled");
                                $("#ri_ntfn_inactive_trigger_" + x).attr("disabled", "disabled");
                                $("#ri_ntfn_any_trigger_" + x).attr("disabled", "disabled");

                            }
                        } else {
                            $("#ri_enable_ntfn_" + x).attr("disabled", "disabled");
                            $("#ri_sound_" + x).attr("disabled", "disabled");
                            $("#ri_ntfn_active_trigger_" + x).attr("disabled", "disabled");
                            $("#ri_ntfn_inactive_trigger_" + x).attr("disabled", "disabled");
                            $("#ri_ntfn_any_trigger_" + x).attr("disabled", "disabled");
                        }
                    }

                    for (var x = 1; x <= 3; x++) {
                        var ro_enabled_x = $("#ro_enabled_" + x).is(':checked');

                        if (ro_enabled_x)
                        {
                            //$("#ro_enable_ntfn_"+x).attr("checked","checked");
                            $("#ro_input_name_" + x).text($("#ro_name_" + x).val());
                            $("#ro_active_label_" + x).text($("#ro_asl_" + x).val());
                            $("#ro_inactive_label_" + x).text($("#ro_iasl_" + x).val());
                            $("#ro_step2_name_" + x).text($("#ro_name_" + x).val());
                            $("#ro_step2_active_label_" + x).text($("#ro_asl_" + x).val());
                            $("#ro_step2_inactive_label_" + x).text($("#ro_iasl_" + x).val());

                            $("#ro_momentary_" + x).attr("disabled", false);
                            if ($("#ro_momentary_" + x).is(":checked")) {
                                $("#ro_active_initialState_" + x).attr("disabled", false);
                                $("#ro_inactive_initialState_" + x).attr("disabled", false);
                                $("#ro_step2_time_" + x).attr("disabled", false);
                            } else {
                                $("#ro_active_initialState_" + x).attr("disabled", "disabled");
                                $("#ro_inactive_initialState_" + x).attr("disabled", "disabled");
                                $("#ro_step2_time_" + x).attr("disabled", "disabled");

                            }

                            $("#ro_enable_ntfn_" + x).attr("disabled", false);
                            $("#ro_ntfn_active_trigger_" + x).attr("disabled", false);
                            $("#ro_ntfn_inactive_trigger_" + x).attr("disabled", false);
                        } else {
                            $("#ro_momentary_" + x).attr("disabled", "disabled");
                            $("#ro_active_initialState_" + x).attr("disabled", "disabled");
                            $("#ro_inactive_initialState_" + x).attr("disabled", "disabled");
                            $("#ro_step2_time_" + x).attr("disabled", "disabled");

                            $("#ro_enable_ntfn_" + x).attr("disabled", "disabled");
                            $("#ro_ntfn_active_trigger_" + x).attr("disabled", "disabled");
                            $("#ro_ntfn_inactive_trigger_" + x).attr("disabled", "disabled");
                        }
                        ro_step2_time = $("#ro_step2_time_" + x).val() ? $("#ro_step2_time_" + x).val() : 1;
                        $("#ro_step2_time_" + x).val(ro_step2_time);
                    }
                });

                $("#ri_enabled_1,#ri_enabled_2,#ri_enabled_3,#ri_enabled_4,#ro_enabled_1,#ro_enabled_2,#ro_enabled_3").click(function() {
                    var this_id = $(this).attr('id');
                    n = this_id.split("_");
                    id_first = n[0];
                    id_last = n[n.length - 1];

                    if ($(this).attr("checked")) {
                        $("#" + id_first + "_name_" + id_last).attr("disabled", false);
                        $("#" + id_first + "_asl_" + id_last).attr("disabled", false);
                        $("#" + id_first + "_iasl_" + id_last).attr("disabled", false);
                    } else {
                        $("#" + id_first + "_name_" + id_last).attr("disabled", "disabled").val("");
                        $("#" + id_first + "_asl_" + id_last).attr("disabled", "disabled").val("");
                        $("#" + id_first + "_iasl_" + id_last).attr("disabled", "disabled").val("");
                    }
                });
                for (var i = 1; i <= 3; i++) {
                    $('#ro_momentary_' + i).click(function() {
                        var this_id = $(this).attr('id');
                        check_momentary_output(this_id);
                    });
                }
                for (var i = 1; i <= 4; i++) {
                $('#ri_enable_ntfn_' + i).click(function() {
                            var this_id = $(this).attr('id');
                            enable_disable_ntfn(this_id);
                        });
                }
                
                function enable_disable_ntfn(id)
                {
                    var arr = id.split('_');
                    var io = arr[0];
                    var ntfn_no = arr[arr.length - 1];
                    var ntfn_id = '#' + io + '_enable_ntfn_' + ntfn_no;

                    if ($(ntfn_id).is(":checked")) {

                        $("input[name=" + io + "_ntfn_trigger_" + ntfn_no + "],input[name=" + io + "_ntfn_sound_" + ntfn_no + "],input[name=" + io + "_ntfn_sms_" + ntfn_no + "], input[name=" + io + "_ntfn_mail_" + ntfn_no + "]").attr("disabled", false);
                    } else {
                        $("input[name=" + io + "_ntfn_trigger_" + ntfn_no + "], input[name=" + io + "_ntfn_sound_" + ntfn_no + "],input[name=" + io + "_ntfn_sms_" + ntfn_no + "],input[name=" + io + "_ntfn_mail_" + ntfn_no + "]").attr("disabled", true);
                    }

                }


            });
        </script>
        <style type="text/css">

            #form_default_remotii_setup .drs_table td, #form_default_remotii_setup .drs_table th{
                text-align: left;
                vertical-align: middle;
                height: 30px;
            }

            .ri_ntfn_trigger{
                text-align: left;
            }
        </style>

    </head>

    <body>
        <form name="form_default_remotii_setup" id="form_default_remotii_setup">	
            <input type="hidden" name="xDefaultRemotiiDataSubmission" value="true">
            <div class="remotii-setup modify"> 
                <h2>Remotii Setup Wizard<span style="float:right;font-size:15px;margin-right:20px;" class="pageno"><span>1</span>/8</span></h2> 
                <div id="slider">
                    <ul>

                        <li>
                            <div>
                                <p style="margin-top: 100px;">Hi.  This wizard will help you set default Remotii setup.<br> We just have a few questions </p>

                                <a class="btn-red drs_cancel" href="#" style="z-index:200000">Cancel</a> 
                            </div>
                        </li>

                        <li>
                            <p style="padding-top: 88px;">In this section, we will configure Remotii inputs.</p>
                        </li>

                        <li>

                            <div class="form rinput">

                                <table width="100%">
                                    <tr>
                                        <td><strong>Enable</strong></td>
                                        <td><strong>Input Names</strong></td>
                                        <td><strong>Active Label</strong></td>
                                        <td><strong>Inactive Label</strong></td>
                                    </tr>

                                    <?php
                                    for ($i = 1; $i <= 4; $i++):
                                        $j = $i; //-1;
                                        if ($spInputConfig[$j]['is_enabled']) {
                                            $checked = 'checked="checked"';
                                            $name = $spInputConfig[$j]['name'];
                                            $activeLabelText = $spInputConfig[$j]['active_label_text'];
                                            $activeLabelColor = $spInputConfig[$j]['active_label_color'];
                                            $inactiveLabelText = $spInputConfig[$j]['inactive_label_text'];
                                            $inactiveLabelColor = $spInputConfig[$j]['inactive_label_color'];
                                            $isEnabled = $spInputConfig[$j]['is_enabled'];
                                            $enableNotification = $spInputConfig[$j]['enable_notification'];
                                            $notificationTrigger = $spInputConfig[$j]['notification_trigger'];
                                            $disabled = '';
                                        } else {
                                            $checked = '';
                                            $name = '';
                                            $activeLabelText = '';
                                            $activeLabelColor = $greenColor;
                                            $inactiveLabelText = '';
                                            $inactiveLabelColor = $redColor;
                                            $isEnabled = '';
                                            $enableNotification = '';
                                            $notificationTrigger = '';
                                            $disabled = 'disabled="disabled"';
                                        }
                                        ?>

                                        <tr class="rsw_v3">
                                            <td><input type="checkbox" <?php echo $checked; ?> name="ri_enabled_<?php echo $i; ?>" id="ri_enabled_<?php echo $i; ?>" ></td>
                                            <td><input <?php echo $disabled; ?> type="text" class="rsw_vr" name="ri_name_<?php echo $i ?>" id="ri_name_<?php echo $i ?>" placeholder="Input<?php echo $i; ?> Name" value="<?php echo $name; ?>"></td>
                                            <td>
                                                <input <?php echo $disabled; ?> type="text" class="rsw_vr" name="ri_asl_<?php echo $i; ?>" id="ri_asl_<?php echo $i; ?>" placeholder="Active Label" value="<?php echo $activeLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $activeLabelColor; ?>" name="ri_active_color_<?php echo $i; ?>"/>
                                                </div>	
                                            </td>
                                            <td>
                                                <input <?php echo $disabled; ?> type="text" class="rsw_vr" name="ri_iasl_<?php echo $i; ?>" id="ri_iasl_<?php echo $i; ?>" placeholder="Inactive Label" value="<?php echo $inactiveLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $inactiveLabelColor; ?>" name="ri_inactive_color_<?php echo $i; ?>"/>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%" class="drs_table">
                                    <tr>
                                        <td style="display:none;"><strong>Pin</strong></td>
                                        <td><strong>Enable Notification</strong></td> 
                                        <td><strong>Notification Trigger</strong></td>
<!--                                                    <td style=" width: 256px; "><strong>Notification Email</strong></td>-->
                                        <td align="center"
                                            ><strong>Play Sound</strong></td>
                                    </tr>
                                    <?php
                                    for ($i = 1; $i <= 4; $i++):
                                        $j = $i; //-1;
                                        if ($spInputConfig[$j]['is_enabled']) {
                                            $name = $spInputConfig[$j]['name'];
                                            $activeLabelText = $spInputConfig[$j]['active_label_text'];
                                            $inactiveLabelText = $spInputConfig[$j]['inactive_label_text'];
                                            $bothLabelText = 'Both';

                                            if ($spInputConfig[$j]['enable_notification']) {
                                                $enableNotification = 'checked="checked"';
                                            } else {
                                                $enableNotification = '';
                                            }

                                            if ($spInputConfig[$j]['notification_sound']) {
                                                $enableNotificationSound = 'checked="checked"';
                                            } else {
                                                $enableNotificationSound = '';
                                            }
                                            $notificationTriggerActive = '';
                                            $notificationTriggerInActive = '';
                                            $notificationTriggerBoth = '';
                                            if ($spInputConfig[$j]['notification_trigger'] == 1) {
                                                $notificationTriggerActive = 'checked="checked"';
                                            } elseif ($spInputConfig[$j]['notification_trigger'] == 2) {
                                                $notificationTriggerBoth = 'checked="checked"';
                                            } elseif ($spInputConfig[$j]['notification_trigger'] == 0) {
                                                $notificationTriggerInActive = 'checked="checked"';
                                            }
                                        } else {
                                            $name = 'Input' . $i;
                                            $activeLabelText = 'Active';
                                            $inactiveLabelText = 'Inactive';
                                            $anyLabelText = 'Both';
                                            $enableNotification = '';
                                            $enableNotificationSound = '';
                                            $notificationTriggerActive = '';
                                            $notificationTriggerInActive = 'checked="checked"';
                                            $notificationTriggerBoth = '';
                                        }
                                        ?>
                                        <tr>
                                            <td style="display:none;">
                                                <input type="hidden" name="ri_pin_number_<?php echo $i; ?>" id="ri_pin_number_<?php echo $i; ?>" value="<?php echo $i; ?>">
                                            </td>
                                            <td style="padding-top: 20px;">
                                                <input <?php echo $enableNotification; ?> name="ri_enable_ntfn_<?php echo $i; ?>" id="ri_enable_ntfn_<?php echo $i; ?>" type="checkbox" >&nbsp;
                                                <label id="ri_input_name_<?php echo $i; ?>"><?php echo $name; ?></label>
                                            </td>
                                            <td class="ri_ntfn_trigger">
                                                <span>
                                                    <input type="radio" value="1" <?php echo $notificationTriggerActive ?> name="ri_ntfn_trigger_<?php echo $i; ?>" id="ri_ntfn_active_trigger_<?php echo $i; ?>">&nbsp;
                                                    <label id="ri_active_label_<?php echo $i ?>">Active</label>
                                                </span>
                                                <span> 
                                                    <input type="radio"  <?php echo $notificationTriggerInActive ?> value="0" name="ri_ntfn_trigger_<?php echo $i; ?>" id="ri_ntfn_inactive_trigger_<?php echo $i; ?>">&nbsp;
                                                    <label id="ri_inactive_label_<?php echo $i ?>">Inactive</label>
                                                </span>
                                                <span>
                                                    <input type="radio" <?php echo $notificationTriggerBoth ?>  value="2" name="ri_ntfn_trigger_<?php echo $i; ?>" id="ri_ntfn_any_trigger_<?php echo $i; ?>">&nbsp;
                                                    <label id="ri_any_label_<?php echo $i ?>">Both</label>    
                                                </span>
                                            </td>
                                            <td align="center" style="padding-top: 20px;"><input <?php echo $enableNotificationSound ?> name="ri_ntfn_sound_<?php echo $i; ?>" id="ri_sound_<?php echo $i; ?>" type="checkbox" value="1" >&nbsp;</td>
                                        </tr>
                                    <?php endfor; ?>
                                </table>
                            </div>
                        </li>


                        <li>
                            <p style="padding-top: 88px;">In this section, we will configure Remotii outputs.</p>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%">
                                    <tr>
                                        <td><strong>Enable</strong></td>
                                        <td><strong>Output Names</strong></td>
                                        <td><strong>Active Label</strong></td>
                                        <td><strong>Inactive Label</strong></td>
                                    </tr>

                                    <?php
                                    for ($i = 1; $i <= 3; $i++):
                                        $j = $i; //-1;
                                        if ($spOutputConfig[$j]['is_enabled']) {
                                            $checked = 'checked="checked"';
                                            $name = $spOutputConfig[$j]['name'];
                                            $activeLabelText = $spOutputConfig[$j]['active_label_text'];
                                            $activeLabelColor = $spOutputConfig[$j]['active_label_color'];
                                            $inactiveLabelText = $spOutputConfig[$j]['inactive_label_text'];
                                            $inactiveLabelColor = $spOutputConfig[$j]['inactive_label_color'];
                                            $isEnabled = $spOutputConfig[$j]['is_enabled'];
                                            $enableNotification = $spOutputConfig[$j]['enable_notification'];
                                            $notificationTrigger = $spOutputConfig[$j]['notification_trigger'];
                                            $disabled = '';
                                        } else {
                                            $checked = '';
                                            $name = '';
                                            $activeLabelText = '';
                                            $activeLabelColor = $greenColor;
                                            $inactiveLabelText = '';
                                            $inactiveLabelColor = $redColor;
                                            $isEnabled = '';
                                            $enableNotification = '';
                                            $notificationTrigger = '';
                                            $disabled = 'disabled="disabled"';
                                        }
                                        ?>

                                        <tr class="rsw_v3">
                                            <td style="display:none;">
                                                <input type="hidden" name="ro_pin_number_<?php echo $i; ?>" id="ro_pin_number_<?php echo $i; ?>" value="<?php echo $i; ?>">
                                            </td>
                                            <td><input <?php echo $checked; ?> type="checkbox" name="ro_enabled_<?php echo $i; ?>" id="ro_enabled_<?php echo $i; ?>" ></td>
                                            <td><input <?php echo $disabled; ?> type="text" class="rsw_vr" name="ro_name_<?php echo $i ?>" id="ro_name_<?php echo $i ?>" placeholder="Output<?php echo $i; ?> Name" value="<?php echo $name; ?>"></td>

                                            <td>
                                                <input <?php echo $disabled; ?> type="text" class="rsw_vr" name="ro_asl_<?php echo $i; ?>" id="ro_asl_<?php echo $i; ?>" placeholder="Active Label" value="<?php echo $activeLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $activeLabelColor ?>" name="ro_active_color_<?php echo $i; ?>"/>
                                                </div>
                                            </td>

                                            <td>
                                                <input <?php echo $disabled; ?> type="text" class="rsw_vr" name="ro_iasl_<?php echo $i; ?>" id="ro_iasl_<?php echo $i; ?>" placeholder="Inactive Label" value="<?php echo $inactiveLabelText; ?>">
                                                <div class="colorPicker">	 
                                                    <input class="noIndColor" value="<?php echo $inactiveLabelColor; ?>" name="ro_inactive_color_<?php echo $i; ?>"/>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div class="form rinput">
                                <table width="100%" class="drs_table">
                                    <tr>
                                        <th><strong>Pin</strong></th>
                                        <th><strong>Output Names</strong></th>
                                        <th><strong>Momentary</strong></th> 
                                        <th><strong>Initial State</strong></th>
                                        <th><strong>Pulse Width (sec)</strong></th>

                                    </tr>
                                    <?php
                                    for ($i = 1; $i <= 3; $i++):
                                        $j = $i; //-1;
                                        if ($spOutputConfig[$j]['is_enabled']) {
                                            $name = $spOutputConfig[$j]['name'];
                                            $activeLabelText = $spOutputConfig[$j]['active_label_text'];
                                            $inactiveLabelText = $spOutputConfig[$j]['inactive_label_text'];
                                            $pulseTime = !empty($spOutputConfig[$j]['pulse_time']) ? $spOutputConfig[$j]['pulse_time'] : 1;

                                            if ($spOutputConfig[$j]['is_output_momentary']) {
                                                $isOutputMomentary = 'checked="checked"';
                                            } else {
                                                $isOutputMomentary = '';
                                            }
                                            $outputInitialStateActive = '';
                                            $outputInitialStateInactive = '';
                                            if ($spOutputConfig[$j]['output_initial_state']) {
                                                $outputInitialStateActive = 'checked="checked"';
                                            } else {
                                                $outputInitialStateInactive = 'checked="checked"';
                                            }
                                        } else {
                                            $name = 'Output' . $i;
                                            $activeLabelText = 'Active';
                                            $inactiveLabelText = 'Inactive';
                                            $outputInitialStateActive = '';
                                            $outputInitialStateInactive = 'checked';
                                            $pulseTime = '1';
                                        }
                                        ?>
                                        <tr>
                                            <td><?php echo $i; ?></td>
                                            <td> <label id="ro_step2_name_<?php echo $i; ?>"><?php echo $name; ?></label> </td>
                                            <td><input type="checkbox" <?php echo $isOutputMomentary ?> pulsee-time="<?php echo $i; ?>" name="ro_momentary_<?php echo $i; ?>" id="ro_momentary_<?php echo $i; ?>"></td>
                                            <td>
                                                <input type="radio" value="1" <?php echo $outputInitialStateActive; ?> id="ro_active_initialState_<?php echo $i; ?>" name="ro_initialState_<?php echo $i; ?>">&nbsp;<label id="ro_step2_active_label_<?php echo $i; ?>"><?php echo $activeLabelText ?> </label>&nbsp;&nbsp;
                                                <input type="radio" value="0"  <?php echo $outputInitialStateInactive; ?> id="ro_inactive_initialState_<?php echo $i; ?>" name="ro_initialState_<?php echo $i; ?>">&nbsp;<label id="ro_step2_inactive_label_<?php echo $i; ?>"><?php echo $inactiveLabelText; ?></label>
                                            </td>
                                            <td><input type="text" value="<?php echo $pulseTime; ?>" id="ro_step2_time_<?php echo $i; ?>" class="pulse-time"  name="ro_pulse_time_<?php echo $i; ?>"></td>
                                        </tr>
                                    <?php endfor; ?>
                                </table>
                            </div>
                        </li>

                        <li>
                            <div id="msg_tpl_1" style="padding-top: 100px;">
                                <p>We’re are all done. Thanks to set a default Remotii setup for your users.</p>
                                <p><a href="#" class="btn2" onclick="return setupRemotii();">Finish</a></p>
                            </div>
                            <div id="setup_finish" style="padding-top: 160px;display:none;"></div>
                        </li>

                    </ul>
                </div>
            </div>

        </form>

        <script type="text/javascript" src="<?php echo BASE_URL . '/assets/c/js/spin.js' ?>"></script>
        <script>

            function setupRemotii()
            {
                target = document.getElementById('setup_finish');
                opts.top = -125;
                var spinner = new Spinner(opts);

                $("#msg_tpl_1").hide();
                $("#setup_finish").html('<span style="font-size:20px;">Setting up remotii....<span>');
                $("#setup_finish").show();
                spinner.spin(target);

                var form_serialized_data = $("#form_default_remotii_setup").serialize();

                //alert(form_serialized_data);

                jQuery.ajax({
                    url: '<?php print BASE_URL . '/sp/default-remotii-setup'; ?>',
                    type: 'post',
                    async: false,
                    data: form_serialized_data,
                    success: function(response) {
                        console.log(response);
                        spinner.stop(target);
                        $("#setup_finish").html('<span style="color:green;font-size:14px;">Your Remotii configuration has been saved.</span>');
                        window.top.location.href = "<?php print BASE_URL . '/sp'; ?>";
                    },
                    /*complete:function(response){
                     console.log( data );
                     }*/
                });
            }

            var opts = {
                lines: 13, // The number of lines to draw
                length: 20, // The length of each line
                width: 10, // The line thickness
                radius: 30, // The radius of the inner circle
                corners: 1, // Corner roundness (0..1)
                rotate: 0, // The rotation offset
                direction: 1, // 1: clockwise, -1: counterclockwise
                color: '#000', // #rgb or #rrggbb or array of colors
                speed: 1, // Rounds per second
                trail: 60, // Afterglow percentage
                shadow: false, // Whether to render a shadow
                hwaccel: false, // Whether to use hardware acceleration
                className: 'spinner', // The CSS class to assign to the spinner
                zIndex: 2e9, // The z-index (defaults to 2000000000)
                top: 'auto', // Top position relative to parent in px
                left: 'auto' // Left position relative to parent in px
            };
        </script>
    </body>
</html>