<div class="pageInfo"><h1>Previous Billing Cycle</h1></div>

<!-- widget -->
<div class="widget">
    <div class="formWrap">
        <div class="box1 hidePars">
            <table cellpadding="0" cellspacing="0" border="0" class="dTable" id="dynamic">
                <thead>
                    <tr>
                        <th>Billing Cycle<span class="sorting" style="display: block;"></span></th>
                        <th> Gross Income</th>
                        <th> Contracted Price</th>
                        <th>Service Fee</th>
                        <th>Net Income</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                    <tr>
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                    
                    <tr>                
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                    <tr>                
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                    <tr>                
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                    <tr>                
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                    <tr>                
                        <td>07/01/2013 - 07/31/2013</td>
                        <td>$11.00</td>
                        <td>$1800.00</td>
                        <td>$80.00</td>
                        <td>$1080.00</td>
                    </tr>
                </tbody>
            </table>
        </div>




    </div>
</div>
<!-- /widget --> 