<body>
    <br>
    <br>
    <br>
    <table cellspacing="0" cellpadding="0" width="800" border="0">
        <tr>
            <td style="text-align:left"><img src="<?php echo BASE_URL; ?>/assets/c/img/logo.png" style="width:130px" alt=""></td>
        </tr>
        <br/>

        <tr>
            <td style="height:5px;"></td>
        </tr>

    </table>

    <br>
<!--
    <p>Hi {NAME}</p>-->
<p> We identified a potential closed loop <b><?php echo $event_name?></b> and slowed it down to avoid hitting server performance. Please verify it manually. To remove the delay, disable and enable the event manually. </p>
    
    <br/>
    <br>
    <br>
    <h3 style="margin:0 0 10px; font-size:14px;">The Remotii Team
        <br />

</body>
