<body style="margin:0; padding:0; color:#3b3a3a; background:#fff; font:normal 15px/26px Arial,elvetica, sans-serif;">
    <br>
    <br>
    <br> 
    <table cellspacing="0" cellpadding="0" width="800" border="0">
        <tr>
            <td style="padding:0px 0 10px 0;"><a href=""><img src="<?php echo BASE_URL; ?>/assets/c/img/logo.png" alt="" /></a></td>        
        </tr>
        <tr>
            <td style="text-align:center; height:45px; line-height:45px; color:#fff; font-size:22px; background:url('<?php echo BASE_URL; ?>/assets/f/images/tag-bg.jpg') no-repeat 50% 0px;">Payment Notification</td>        
        </tr>
        <tr>
            <td style="padding:10px 0 0 0;"> 
                <?php print $this->name; ?>
                <br/> 
                <?php print $this->nxtBillDate; ?>
                <br/>
                <?php print $this->msg; ?>
            </td>        
        </tr> 
        <tr>
            <td style="padding:15px 0 0 0;">Thank you for your business,<br/><b><?php print $this->rsp; ?></b></td> 
        </tr>
    </table>
</body>