<body>
    <br>
    <br>
    <br>
    <table cellspacing="0" cellpadding="0" width="800" border="0">
        <tr>
            <td style="text-align:left"><img src="<?php echo BASE_URL; ?>/assets/c/img/logo.png" style="width:130px" alt=""></td>
        </tr>
        <br/>
        <tr>
            <td style="text-align:center; height:45px; line-height:45px; color:#fff; font-size:22px; background:url('<?php echo BASE_URL; ?>/assets/f/images/tag-bg.jpg') no-repeat 50% 0px; font-family:arial;">		Offline Notification for <?php print $this->remotii_name; ?></td>
        </tr>
        <tr>
            <td style="height:5px;"></td>
        </tr>
        
    </table>
    <br>
    <h3 style="margin:0 0 10px; font-size:14px;">Dear <?php echo $this->name;?>,</h3>
    <h3 style="margin:0 0 10px; font-size:14px;">As per your Remotii <?php echo $this->remotii_name;?> configuration, your device appears to be offline. The last communication with the server occurred at time <?php echo $this->remotii_last_communication_time;?>. Please check your Internet connection.</h3>
    <span style="font-size:10px">If you no longer wish to receive notification emails, you may disable future notifications by logging in to your Remotii account and stepping through the Remotii configuration wizard for the Remotii(s) in question.</span>
    <br/>
    <br>
    <br>
    <h3 style="margin:0 0 10px; font-size:14px;">The Remotii Team
        <br />

</body>
