<body>
    <br>
    <br>
    <br>
    <table cellspacing="0" cellpadding="0" width="800" border="0">
        <tr>
            <td style="text-align:left"><img src="<?php echo BASE_URL; ?>/assets/c/img/logo.png" style="width:130px" alt=""></td>
        </tr>
        <br/>

        <tr>
            <td style="height:5px;"></td>
        </tr>

    </table>

    <br>
<!--
    <p>Hi {NAME}</p>-->
    <p>This email is to inform you that Remotii: '<?php echo $remotii_name;?>' has been removed or is no longer shared with full control. Consequently, the following chained events have also been removed: </p>
    <table style="border-collapse: separate; border-spacing: 2px; border-color: gray" cellpadding="0" cellspacing="0" border="0" class="table1" width="100%">
        <thead>
            <tr class="odd">
                <th style="background: #4c4c4c;color: #fff;text-align: left;padding-left: 10px;height: 25px;font-family:arial;">Event Name</th>
                <th style="background: #4c4c4c;color: #fff;text-align: left;padding-left: 10px;height: 25px;font-family:arial;">Source Remotii</th>
                <th style="background: #4c4c4c;color: #fff;text-align: left;padding-left: 10px;height: 25px;font-family:arial;">Destination Remotii</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($chainedEvents as $key){?>
            <tr>
                <td><?php echo $key['event_name'];?></td>
                <td><?php echo $key['source'];?></td>
                <td><?php echo $key['destination'];?></td>
            </tr>
            <?php }?>
        </tbody>
    </table>
    <br>
    <!--<span style="font-size:10px">If you no longer wish to receive notification emails, you may disable future notifications by logging in to your Remotii account and stepping through the Remotii configuration wizard for the Remotii(s) in question.</span>-->
    <br/>
    <br>
    <br>
    <h3 style="margin:0 0 10px; font-size:14px;">The Remotii Team
        <br />

</body>
