<body>
    <br>
    <br>
    <br>
    <table cellspacing="0" cellpadding="0" width="800" border="0">
        <tr>
            <td style="text-align:left"><img src="<?php echo BASE_URL; ?>/assets/c/img/logo.png" style="width:130px" alt=""></td>
        </tr>
        <br/>
        <tr>
            <td style="text-align:center; height:45px; line-height:45px; color:#fff; font-size:22px; background:url('<?php echo BASE_URL; ?>/assets/f/images/tag-bg.jpg') no-repeat 50% 0px; font-family:arial;">		Event Notification for <?php print $bitInfo['remotii_name']; ?></td>
        </tr>
        <tr>
            <td style="height:5px;"></td>
        </tr>
        <tr>
            <td>
                <table style="border-collapse: separate; border-spacing: 2px; border-color: gray" cellpadding="0" cellspacing="0" border="0" class="table1" width="100%">
                    <thead>
                        <tr class="odd">
                            <th style="background: #4c4c4c;color: #fff;text-align: left;padding-left: 10px;height: 50px;font-family:arial;">Event Time</th>
                            <th style="background: #4c4c4c;color: #fff;text-align: left;padding-left: 10px;height: 50px;font-family:arial;">Input Status</th>
                            <th style="background: #4c4c4c;color: #fff;text-align: left;padding-left: 10px;height: 50px;font-family:arial;">Output Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="padding: 10px; vertical-align: top;font-family:arial;border-bottom: 1px solid #DDDDDD; border-right: 1px solid #DDDDDD; border-left: 1px solid #DDDDDD;">
                                <p style="margin:0;font-family:arial; color:#656565;"> <?php echo $outTime ?> </p>
                            </td>
                            <td style="padding: 10px;vertical-align: top;border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;">
                                <table>
                                    <tbody>
                                        <?php
                                        $i = 1;
                                        $inHt = '';
                                        $Starthtml = "<td style='margin:0;font-family:arial;'>";
                                        $endhtml = "</td>";
                                        foreach ($inputConfig as $inConfig) {
                                            ?>
                                            <tr <?php if ($trigger_pin == $inConfig['pin_number']) { ?>
                                                    style="color:red; font-weight:bold"
                                                <?php } ?>>

                                                <?php
                                                if ($inState & pow(2, ((int) $inConfig['pin_number']) - 1)) {
                                                    $inHt = $Starthtml . $inConfig['name'] . $endhtml . $Starthtml . ' : ' . $inConfig['active_label_text'] . $endhtml;
                                                } else {
                                                    $inHt = $Starthtml . $inConfig['name'] . $endhtml . $Starthtml . ' : ' . $inConfig['inactive_label_text'] . $endhtml;
                                                }
//                                    if ($trigger_pin == $inConfig['pin_number']) { // trigger
//                                        $inHt = '<span style="color:red; font-weight:bold">' . $inHt . '</span>';
//                                    }

                                                echo $inHt;
                                                ?> </tr> <?php
                                            $i++;
                                        }
                                        ?>
                                    </tbody>
                                </table>
                            </td>
                            <td style="padding: 10px;vertical-align: top; border-right: 1px solid #DDDDDD;border-bottom: 1px solid #DDDDDD;">
                                <table>
                                    <tbody>
                                        <?php
                                        $Starthtml = "<td style='margin:0;font-family:arial;'>";
                                        $endhtml = "</td>";
                                        $j = 1;
                                        foreach ($outputConfig as $outConfig) {
                                            ?>
                                            <tr> <?php
                                                if ($outState & pow(2, ((int) $outConfig['pin_number']) - 1)) {
                                                    $inHt = $Starthtml . $outConfig['name'] . $endhtml . $Starthtml . ' : ' . $outConfig['active_label_text'] . $endhtml;
                                                } else {
                                                    //inactive
                                                    $inHt = $Starthtml . $outConfig['name'] . $endhtml . $Starthtml . ' : ' . $outConfig['inactive_label_text'] . $endhtml;
                                                }

                                                //$inHt = "<p style='margin:0;font-family:arial; '>" . $inHt . "</p>";
                                                echo $inHt;
                                                ?> </tr> <?php
                                                $j++;
                                            }
                                            ?>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

    </table>
    <br>
    <h3 style="margin:0 0 10px; font-size:14px;">This email is to inform you that one or more of your Remotii trigger conditions have been met. </h3>
    <span style="font-size:10px">If you no longer wish to receive notification emails, you may disable future notifications by logging in to your Remotii account and stepping through the Remotii configuration wizard for the Remotii(s) in question.</span>
    <br/>
    <br>
    <br>
    <h3 style="margin:0 0 10px; font-size:14px;">The Remotii Team
        <br />

</body>