<?php
$baseUrl = BASE_URL . '/assets/b';
echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Remotii')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->

        <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>-->
        <?php
        echo $this->headMeta()->appendName("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", "viewport");
        echo $this->headLink()->appendStylesheet($baseUrl . '/css/styles.css');
        echo $this->headLink()->appendStylesheet($baseUrl . '/css/main-phase2.css');

        echo $this->headScript()
                ->prependFile($baseUrl . '/js/jquery.min.js')
                ->appendFile($baseUrl . '/js/jquery-ui.min.js')
                ->appendFile($baseUrl . '/js/custom.js')
                ->appendFile($baseUrl . '/js/jquery.maskedinput-1.3.min.js')
                ->appendFile($baseUrl . '/js/plugins/forms/ui.spinner.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.mousewheel.js')
                ->appendFile($baseUrl . '/js/plugins/charts/excanvas.min.js')
                ->appendFile($baseUrl . '/js/plugins/charts/jquery.flot.js')
                ->appendFile($baseUrl . '/js/plugins/charts/jquery.flot.orderBars.js')
                ->appendFile($baseUrl . '/js/plugins/charts/jquery.flot.pie.js')
                ->appendFile($baseUrl . '/js/plugins/charts/jquery.flot.resize.js')
                ->appendFile($baseUrl . '/js/plugins/charts/jquery.sparkline.min.js')
                ->appendFile($baseUrl . '/js/plugins/tables/jquery.dataTables.js')
                ->appendFile($baseUrl . '/js/plugins/tables/jquery.sortable.js')
                ->appendFile($baseUrl . '/js/plugins/tables/jquery.resizable.js')
                ->appendFile($baseUrl . '/js/plugins/forms/autogrowtextarea.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.uniform.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.inputlimiter.min.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.tagsinput.min.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.maskedinput.min.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.autotab.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.chosen.min.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.dualListBox.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.cleditor.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.ibutton.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.validationEngine-en.js')
                ->appendFile($baseUrl . '/js/plugins/forms/jquery.validationEngine.js')
                ->appendFile($baseUrl . '/js/plugins/uploader/plupload.js')
                ->appendFile($baseUrl . '/js/plugins/uploader/plupload.html4.js')
                ->appendFile($baseUrl . '/js/plugins/uploader/plupload.html5.js')
                ->appendFile($baseUrl . '/js/plugins/uploader/jquery.plupload.queue.js')
                ->appendFile($baseUrl . '/js/plugins/wizards/jquery.form.wizard.js')
                ->appendFile($baseUrl . '/js/plugins/wizards/jquery.validate.js')
                ->appendFile($baseUrl . '/js/plugins/wizards/jquery.form.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.collapsible.min.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.breadcrumbs.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.tipsy.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.progress.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.timeentry.min.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.colorpicker.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.jgrowl.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.fancybox.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.fileTree.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.sourcerer.js')
                ->appendFile($baseUrl . '/js/plugins/others/jquery.fullcalendar.js')
                ->appendFile($baseUrl . '/js/plugins/others/jquery.elfinder.js')
                ->appendFile($baseUrl . '/js/plugins/ui/jquery.easytabs.min.js')
                ->appendFile($baseUrl . '/js/files/bootstrap.js')
                ->appendFile($baseUrl . '/js/files/functions.js')
                //->appendFile($baseUrl . '/js/charts/chart.js')
                //->appendFile($baseUrl . '/js/charts/hBar_side.js')
               
                ->prependScript('BASE_URL = "' . BASE_URL . '";');
        echo $this->headStyle();
        echo $this->session()->warningBeforeSessionTimeout(array(
            'sls' => ADMIN_SESSION_TIMEOUT,
            'wls' => SESSION_TIMEOUT_WARNING_LENGTH,
            'logoutUrl' => BASE_URL . '/logout'));
        echo $this->headStyle();
        ?>
        <script type="text/javascript" src="<?php echo BASE_URL ?>/assets/c/js/html5placeholder.jquery.js"></script>
        <script>
            $(function() {
                $(':input[placeholder]').placeholder();
            });
        </script>
    </head>
    <body>
        <!-- Header Added -->
        <!-- Top line begins -->
        <?php echo $this->partial("remotii-administrator/header"); ?>
        <!-- Top line ends --> 

        <!-- container begins -->
        <div class="container"> 
            <!-- Sidebar begins -->
            <?php
            if ($this->zfcUserIdentity()) {
                echo $this->partial("remotii-administrator/sidebar");
            }
            ?>
            <!-- Sidebar ends --> 

            <!-- Content begins -->
            <div id="content">
                <div class="wrapper">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <!-- Content ends --> 
        </div>
        <!-- container end -->

        <!-- Footer added -->
        <?php echo $this->partial("remotii-administrator/footer"); ?>


    </body>

</body>
</html>
