<div class="wrapper">
	<h2>Create User Account</h2>
	<div class="box1">
		<div class="inner form">
			<h4>Your Account Info <span>(All fields are required)</span></h4>
			<form>
				<ul>
					<li><input type="text" placeholder="Username"></li>
					<li><input type="text" placeholder="First Name"></li>
					<li><input type="text" placeholder="Last Name"></li>
					<li><input type="text" placeholder="Phone Number"></li>
					<li><input type="text" placeholder="Email Address"></li>
				</ul>
				<h4>Set Password</h4>
				<ul>
					<li><input type="password" placeholder="Password">
						<span>Passwords must be at least 8 characters and include at least one number, special characters, or upper case letter.</span>
					</li>
					<li><input type="password" placeholder="Verify Password"></li>
				</ul>
				<h4>Address</h4>
				<ul>
					<li><input type="text" placeholder="Street"></li>
					<li><input type="text" placeholder="City"></li>
					<li><input type="text" placeholder="State" class="half">
						<input type="text" placeholder="Zip Code"  class="half">
					</li>
					
				</ul>
				<h4>Payment Source Details </h4>
				<ul>
					<li><input type="text" placeholder="Credit Card Number"></li>
					<li><input type="text" placeholder="CVV" class="one-third">
						<input type="text" placeholder="Expiry Month" class="one-third">
						<input type="text" placeholder="Expiry Year" class="one-third">
					</li>
					<li>
						Thank you for choosing Remotii.  By signing up, you hereby agree to the <br>
<a href="#">"Remotii Terms of Service".</a>

					</li>
					
				</ul>
				<input type="submit" title="Create Account" name="submit" value="Create Account" class="submit-btn">
			</form>
		</div>
	</div>
</div>