
<div class="tag-line">
  <div class="wrapper">   
    <h2>Forgot Password</h2>
  </div>
</div>

<div class="wrapper" style="min-height: 400px;">
	<div class="box1" style="width:650px;">
		<div class="inner form" style="padding:40px 30px;">
		
			<h1>Your password has been changed.</h1>
			
			<p>You can now login using your new password.</p>
			
			<a href="<?php echo $this->url('zfcuser/login') ?>">Back to login.</a>
	
		</div>
	</div>
</div>