
<div class="tag-line">
  <div class="wrapper">   
    <h2>Reset Password</h2>
  </div>
</div>



<div class="wrapper" style="min-height: 400px;"><br>
<h3>Change Password for <?php echo $this->escapeHtml($this->email); ?></h3>
	<div class="box1" style="width:650px;">
		<div class="inner form" style="padding:40px 30px;">
<?php

$form = $this->resetForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/resetpassword', array('userId' => $this->userId, 'token' => $this->token)));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>
<div>
<p><?php echo $this->formLabel($form->get('newCredential')); ?></p>

<p><?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'),array('class'=>'error')); ?> </p>

<p><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></p>

<p><?php
echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'),array('class'=>'error'));
?></p>

<p><?php
echo $this->formButton($form->get('submit')->setAttribute('class','btn1'));
?></p>

</div>

<?php echo $this->form()->closeTag(); ?>

	</div>
</div>
</div>
