
<div class="tag-line">
  <div class="wrapper">   
    <h2>Forgot your password?</h2>
  </div>
</div>

<div class="wrapper" style="min-height: 400px;">
	<div class="box1" style="width:650px;">
		<div class="inner form" style="padding:40px 30px;">

			<p>A reminder has been sent to your e-mail address <?php echo $this->escapeHtml($this->email); ?></p>
			
			<a href="<?php echo $this->url('zfcuser/login') ?>">Back to login?</a>
		
		</div>
	</div>
</div>