<div class="footer-link">
    <div class="wrapper">
        <ul>
            <li>
                <h3>Explore</h3>
                <a href="<?php echo BASE_URL?>/remotii-uses">Remotii Uses</a>
            </li>
            <li>
                <h3>Information</h3>
                <a href="<?php echo BASE_URL?>/getting-started">Getting Started</a>
            </li>
            <li>
                <h3>Legal</h3>
                <a href="<?php echo BASE_URL?>/terms-and-conditions">Terms and Conditions</a>
            </li>
        </ul>
    </div>
</div>
<!--/footer link-->
<div class="footer">
    <div class="wrapper">
        <p>Copyright 2012 - 2018 Remotii. All Rights Reserved.</p>
    </div>
</div>